import { eq, inArray } from "drizzle-orm";
import { afterEach, describe, expect, it } from "vitest";
import { capabilityApplicationDocuments, capabilityApplicationFunctions, capabilityApplications, capabilityAuditRecords, capabilityDecisionNotifications, capabilityGrantFunctions, capabilityGrants, userAccountProfiles, users } from "../../drizzle/schema";
import { addCapabilityApplicationDocument, createPasswordUser, db, getAdminCapabilityGovernanceData, getCapabilityApplicantWorkspace, getCapabilityCatalog, saveCapabilityApplication } from "./db";

const cleanupUserIds: number[] = [];

afterEach(async () => {
  if (!cleanupUserIds.length) return;
  const profiles = await db().select().from(userAccountProfiles).where(inArray(userAccountProfiles.userId, cleanupUserIds)); const profileIds = profiles.map(row => row.id);
  const applications = profileIds.length ? await db().select().from(capabilityApplications).where(inArray(capabilityApplications.userAccountProfileId, profileIds)) : []; const applicationIds = applications.map(row => row.id);
  const grants = profileIds.length ? await db().select().from(capabilityGrants).where(inArray(capabilityGrants.userAccountProfileId, profileIds)) : []; const grantIds = grants.map(row => row.id);
  if (applicationIds.length) await db().delete(capabilityApplicationDocuments).where(inArray(capabilityApplicationDocuments.applicationId, applicationIds));
  if (applicationIds.length) await db().delete(capabilityAuditRecords).where(inArray(capabilityAuditRecords.applicationId, applicationIds));
  if (grantIds.length) await db().delete(capabilityAuditRecords).where(inArray(capabilityAuditRecords.grantId, grantIds));
  if (cleanupUserIds.length) await db().delete(capabilityAuditRecords).where(inArray(capabilityAuditRecords.actorUserId, cleanupUserIds));
  if (applicationIds.length) await db().delete(capabilityApplicationFunctions).where(inArray(capabilityApplicationFunctions.applicationId, applicationIds));
  if (grantIds.length) await db().delete(capabilityGrantFunctions).where(inArray(capabilityGrantFunctions.grantId, grantIds));
  if (cleanupUserIds.length) await db().delete(capabilityDecisionNotifications).where(inArray(capabilityDecisionNotifications.userId, cleanupUserIds));
  if (applicationIds.length) await db().delete(capabilityApplications).where(inArray(capabilityApplications.id, applicationIds));
  await db().delete(users).where(inArray(users.id, cleanupUserIds)); cleanupUserIds.splice(0);
});

describe("Stage 5/6 remediation: detailed applications and administrative review filters", () => {
  it("persists bounded role-specific data, protects document ownership, and filters the administrator queue server-side", async () => {
    const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const csrApplicant = await createPasswordUser({ name: "Stage 56 CSR Applicant", email: `stage56-csr-${suffix}@fitizen.test`, passwordHash: "stage56-test-only" }); const authorityApplicant = await createPasswordUser({ name: "Stage 56 Authority Applicant", email: `stage56-authority-${suffix}@fitizen.test`, passwordHash: "stage56-test-only" }); expect(csrApplicant && authorityApplicant).toBeTruthy(); cleanupUserIds.push(csrApplicant!.id, authorityApplicant!.id);
    const catalog = await getCapabilityCatalog(); const csr = catalog.find(item => item.capability.code === "CSR_SPONSORSHIP"); const authority = catalog.find(item => item.capability.code === "LOCAL_AUTHORITY"); expect(csr && authority).toBeTruthy();
    const startsAt = new Date("2030-05-01T00:00:00.000Z"); const endsAt = new Date("2030-06-01T00:00:00.000Z"); const csrFunctions = csr!.functions.filter(item => item.isMandatory).map(item => item.id); const authorityFunctions = authority!.functions.filter(item => item.isMandatory).map(item => item.id);
    await expect(saveCapabilityApplication(csrApplicant!.id, { capabilityId: csr!.capability.id, functionIds: csrFunctions, justification: "A controlled sponsor capability request used to verify required role-specific company data validation.", scopeType: "city", city: "Mumbai", startsAt, endsAt, roleSpecificData: { companyName: "Missing mandatory CSR data" } })).rejects.toThrow("Complete the required CSR");
    const csrApplication = await saveCapabilityApplication(csrApplicant!.id, { capabilityId: csr!.capability.id, functionIds: csrFunctions, justification: "A controlled sponsor capability request for a documented Mumbai community programme, retained only for Stage 5/6 verification.", scopeType: "city", city: "Mumbai", startsAt, endsAt, roleSpecificData: { companyName: "Stage 56 Foundation", registrationNumber: "CIN-STAGE56", contactPerson: "CSR Officer", officialEmail: "csr.officer@stage56.test", mobile: "9876543210", programmeName: "Mumbai Community Movement", fundsAvailable: "500000", proposalPurpose: "Fund verified community movement activities with accountable local delivery.", proposedActivity: "Community fitness events", serviceArea: "Mumbai", expectedParticipants: "500", expectedImpact: "Increase access to inclusive movement opportunities through measured programme participation.", declarationAccepted: "true", transactionStatus: "planned" } });
    const document = await addCapabilityApplicationDocument(csrApplicant!.id, csrApplication.id, { storageKey: `capability-applications/${csrApplicant!.id}/${csrApplication.id}/registration.pdf`, fileName: "registration.pdf", contentType: "application/pdf", sizeBytes: 2_048 }); expect(document.fileName).toBe("registration.pdf"); await expect(addCapabilityApplicationDocument(authorityApplicant!.id, csrApplication.id, { storageKey: `capability-applications/${authorityApplicant!.id}/${csrApplication.id}/foreign.pdf`, fileName: "foreign.pdf", contentType: "application/pdf", sizeBytes: 2_048 })).rejects.toThrow("Supporting documents");
    const authorityApplication = await saveCapabilityApplication(authorityApplicant!.id, { capabilityId: authority!.capability.id, functionIds: authorityFunctions, justification: "A controlled authority capability application that verifies designated official applicant details and filter isolation.", scopeType: "city", city: "Delhi", startsAt: new Date("2030-07-01T00:00:00.000Z"), endsAt: new Date("2030-08-01T00:00:00.000Z"), roleSpecificData: { authorityName: "Stage 56 Authority", department: "Public Health", officerName: "Authority Officer", officialId: "OFF-56", officialEmail: "authority.officer@stage56.test", officialMobile: "9876543210" } });
    const ownWorkspace = await getCapabilityApplicantWorkspace(csrApplicant!.id); const ownRow = ownWorkspace.applications.find(row => row.application.id === csrApplication.id); expect(ownRow?.application.roleSpecificData).toMatchObject({ companyName: "Stage 56 Foundation", serviceArea: "Mumbai" }); expect(ownRow?.documents.map(item => item.fileName)).toEqual(["registration.pdf"]); const otherWorkspace = await getCapabilityApplicantWorkspace(authorityApplicant!.id); expect(otherWorkspace.applications.flatMap(row => row.documents).map(item => item.id)).not.toContain(document.id);
    const filtered = await getAdminCapabilityGovernanceData({ status: "draft", capability: "CSR_SPONSORSHIP", applicant: "Stage 56 CSR", geography: "Mumbai", requestedFrom: new Date("2030-05-01T00:00:00.000Z"), requestedTo: new Date("2030-06-01T00:00:00.000Z") }); expect(filtered.applications.map(row => row.application.id)).toEqual([csrApplication.id]); expect(filtered.applications[0].documents.map(item => item.id)).toEqual([document.id]); expect(filtered.applications[0].application.roleSpecificData).toMatchObject({ programmeName: "Mumbai Community Movement" }); expect(filtered.applications.map(row => row.application.id)).not.toContain(authorityApplication.id);
    const documentRow = (await db().select().from(capabilityApplicationDocuments).where(eq(capabilityApplicationDocuments.id, document.id)).limit(1))[0]; expect(documentRow.storageKey).toContain(`capability-applications/${csrApplicant!.id}/`);
  }, 60_000);
});
