import { eq, inArray } from "drizzle-orm";
import { afterEach, describe, expect, it } from "vitest";
import { capabilityAuditRecords, capabilityDecisionNotifications, capabilityGrantFunctions, capabilityGrantReminderDeliveries, capabilityGrants, categories, events, participantHistoryAuditRecords, participantHistoryConsents, participantHistoryCorrections, participantHistoryEntries, registrations, userAccountProfiles, users } from "../../drizzle/schema";
import { adminReviewCapabilityApplication, createParticipantHistoryCorrection, createParticipantHistoryEntry, createPasswordUser, db, deliverExpiringAuthorityGrantReminders, findUserByEmail, getAuthorityHealthAnalytics, getCapabilityCatalog, getExpiringAuthorityGrantAlerts, saveCapabilityApplication, setParticipantHealthConsent, submitCapabilityApplication } from "./db";

const cleanupUserIds: number[] = [];
const cleanupEventIds: number[] = [];

afterEach(async () => {
  if (!cleanupUserIds.length) return;
  const profiles = await db().select().from(userAccountProfiles).where(inArray(userAccountProfiles.userId, cleanupUserIds)); const profileIds = profiles.map(row => row.id); const grants = profileIds.length ? await db().select().from(capabilityGrants).where(inArray(capabilityGrants.userAccountProfileId, profileIds)) : []; const grantIds = grants.map(row => row.id); const entries = await db().select().from(participantHistoryEntries).where(inArray(participantHistoryEntries.userId, cleanupUserIds)); const entryIds = entries.map(row => row.id);
  if (entryIds.length) await db().delete(participantHistoryAuditRecords).where(inArray(participantHistoryAuditRecords.entryId, entryIds));
  if (cleanupUserIds.length) await db().delete(participantHistoryAuditRecords).where(inArray(participantHistoryAuditRecords.actorUserId, cleanupUserIds));
  if (entryIds.length) await db().delete(participantHistoryCorrections).where(inArray(participantHistoryCorrections.originalEntryId, entryIds));
  if (entryIds.length) await db().delete(participantHistoryEntries).where(inArray(participantHistoryEntries.id, entryIds));
  if (cleanupUserIds.length) await db().delete(participantHistoryConsents).where(inArray(participantHistoryConsents.userId, cleanupUserIds));
  if (grantIds.length) await db().delete(capabilityGrantReminderDeliveries).where(inArray(capabilityGrantReminderDeliveries.grantId, grantIds));
  if (cleanupUserIds.length) await db().delete(capabilityDecisionNotifications).where(inArray(capabilityDecisionNotifications.userId, cleanupUserIds));
  if (grantIds.length) await db().delete(capabilityAuditRecords).where(inArray(capabilityAuditRecords.grantId, grantIds));
  if (grantIds.length) await db().delete(capabilityGrantFunctions).where(inArray(capabilityGrantFunctions.grantId, grantIds));
  if (cleanupUserIds.length) await db().delete(registrations).where(inArray(registrations.attendeeId, cleanupUserIds));
  if (cleanupEventIds.length) await db().delete(events).where(inArray(events.id, cleanupEventIds));
  await db().delete(users).where(inArray(users.id, cleanupUserIds)); cleanupUserIds.splice(0); cleanupEventIds.splice(0);
});

describe("Stage 10 consented append-only participant history", () => {
  it("keeps manual daily history immutable, restricts aggregate analytics to an exact selected grant, and deduplicates reminders", async () => {
    const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const participant = await createPasswordUser({ name: "Stage Ten Participant", email: `stage10-participant-${suffix}@fitizen.test`, passwordHash: "stage10-test-only" }); const authority = await createPasswordUser({ name: "Stage Ten Authority", email: `stage10-authority-${suffix}@fitizen.test`, passwordHash: "stage10-test-only" }); expect(participant && authority).toBeTruthy(); cleanupUserIds.push(participant!.id, authority!.id);
    const wellness = (await db().select().from(categories).where(eq(categories.slug, "wellness")).limit(1))[0]; expect(wellness).toBeTruthy(); const now = new Date(); const eventResult = await db().insert(events).values({ organizerId: participant!.id, organizerPublicId: participant!.publicId, publicId: `EVT-ST10-${suffix}`.slice(0, 24), categoryId: wellness!.id, title: "Stage Ten wellness event", displayName: "Stage Ten wellness", slug: `stage-ten-wellness-${suffix}`, status: "live", moderationStatus: "approved", startsAt: now, endsAt: new Date(now.getTime() + 86_400_000), timezone: "Asia/Calcutta", city: "Stage Ten City" }); const eventId = Number(eventResult[0].insertId); cleanupEventIds.push(eventId);
    const registrationResult = await db().insert(registrations).values({ eventId, attendeeId: participant!.id, attendeePublicId: participant!.publicId, orderNumber: `ST10-${suffix}`, status: "confirmed", paymentStatus: "not_required" }); const registrationId = Number(registrationResult[0].insertId); const entryDate = now.toISOString().slice(0, 10);
    await expect(createParticipantHistoryEntry(participant!.id, { registrationId, entryDate, payload: { wellbeing: "good", energyLevel: "4", comfort: "comfortable" } })).rejects.toThrow("consent"); await setParticipantHealthConsent(participant!.id, true);
    const entry = await createParticipantHistoryEntry(participant!.id, { registrationId, entryDate, payload: { wellbeing: "good", energyLevel: "4", comfort: "comfortable", note: "Manual Stage Ten entry" } }); expect(entry.publicId).toMatch(/^HEN-[A-F0-9]{16}$/); await expect(createParticipantHistoryEntry(participant!.id, { registrationId, entryDate, payload: { wellbeing: "good", energyLevel: "4", comfort: "comfortable" } })).rejects.toThrow(); const correction = await createParticipantHistoryCorrection(participant!.id, { entryId: entry.id, reason: "The energy level was entered incorrectly in the original record.", payload: { wellbeing: "great", energyLevel: "5", comfort: "comfortable" } }); expect(correction.publicId).toMatch(/^HCR-[A-F0-9]{16}$/); const original = (await db().select().from(participantHistoryEntries).where(eq(participantHistoryEntries.id, entry.id)).limit(1))[0]; expect(original.payload).toMatchObject({ wellbeing: "good", energyLevel: 4 });
    const admin = await findUserByEmail("admin@fitizen.local"); expect(admin?.role).toBe("admin"); const catalog = await getCapabilityCatalog(); const district = catalog.find(item => item.capability.code === "DISTRICT_LEVEL"); const selectedFunctionIds = district!.functions.filter(item => item.isMandatory || item.code === "DISTRICT_HEALTH_AGGREGATE_VIEW").map(item => item.id); const application = await saveCapabilityApplication(authority!.id, { capabilityId: district!.capability.id, functionIds: selectedFunctionIds, justification: "Stage Ten scoped aggregate health analytics verification with no individual record access.", scopeType: "city", city: "Stage Ten City", startsAt: new Date(now.getTime() - 60_000), endsAt: new Date(now.getTime() + 5 * 86_400_000) }); await submitCapabilityApplication(authority!.id, application.id, "Ready for isolated Stage Ten authority review"); const approved = await adminReviewCapabilityApplication(admin!.id, { applicationId: application.id, decision: "approved", note: "Approved for Stage Ten aggregate-only scoped verification.", selectedFunctionIds, scope: { scopeType: "city", city: "Stage Ten City" }, startsAt: new Date(now.getTime() - 60_000), endsAt: new Date(now.getTime() + 5 * 86_400_000) }); const grantId = approved.grant!.id;
    const analytics = await getAuthorityHealthAnalytics(authority!.id, "DISTRICT_LEVEL", grantId); expect(analytics?.totalEntries).toBe(1); expect(analytics?.byWellbeing).toEqual([{ label: "good", count: 1 }]); await expect(getAuthorityHealthAnalytics(participant!.id, "DISTRICT_LEVEL", grantId)).rejects.toThrow("active"); const alerts = await getExpiringAuthorityGrantAlerts(authority!.id); expect(alerts.map(alert => alert.grantId)).toContain(grantId); expect((await deliverExpiringAuthorityGrantReminders(now)).processed).toBeGreaterThanOrEqual(1); expect((await deliverExpiringAuthorityGrantReminders(now)).processed).toBe(0);
  }, 90_000);
});
