import { eq, inArray } from "drizzle-orm";
import { afterEach, describe, expect, it } from "vitest";
import { capabilityApplications, capabilityAuditRecords, capabilityDecisionNotifications, capabilityGrantFunctions, capabilityGrants, csrBudgets, csrCapabilitySponsorships, csrEventAssignments, csrFutureEventConcepts, csrProfiles, csrSponsorshipRequests, userAccountProfiles, userWorkspacePreferences, users } from "../../drizzle/schema";
import { adminAssignCsrCapabilityRequest, adminRecordCsrCapabilityFunding, adminReviewCapabilityApplication, adminReviewCsrCapabilityRequest, createPasswordUser, csrCreateCapabilityBudget, csrSaveCapabilitySponsorshipRequest, csrSubmitCapabilitySponsorshipRequest, db, findUserByEmail, getCapabilityCatalog, getCsrCapabilityAssignedParticipants, getCsrCapabilityWorkspaceData, getWorkspaceLandingPreference, saveCsrCapabilityProfile, saveWorkspaceLandingPreference, saveCapabilityApplication, submitCapabilityApplication } from "./db";

const cleanupUserIds: number[] = [];

afterEach(async () => {
  if (!cleanupUserIds.length) return;
  const profiles = await db().select().from(userAccountProfiles).where(inArray(userAccountProfiles.userId, cleanupUserIds)); const profileIds = profiles.map(item => item.id);
  const grants = profileIds.length ? await db().select().from(capabilityGrants).where(inArray(capabilityGrants.userAccountProfileId, profileIds)) : []; const grantIds = grants.map(item => item.id);
  const csr = await db().select().from(csrProfiles).where(inArray(csrProfiles.userId, cleanupUserIds)); const csrIds = csr.map(item => item.id);
  const requests = csrIds.length ? await db().select().from(csrSponsorshipRequests).where(inArray(csrSponsorshipRequests.csrProfileId, csrIds)) : []; const requestIds = requests.map(item => item.id);
  const sponsorships = requestIds.length ? await db().select().from(csrCapabilitySponsorships).where(inArray(csrCapabilitySponsorships.requestId, requestIds)) : []; const sponsorshipIds = sponsorships.map(item => item.id);
  if (sponsorshipIds.length) await db().delete(csrEventAssignments).where(inArray(csrEventAssignments.sponsorshipId, sponsorshipIds));
  if (requestIds.length) await db().delete(csrFutureEventConcepts).where(inArray(csrFutureEventConcepts.requestId, requestIds));
  if (sponsorshipIds.length) await db().delete(csrCapabilitySponsorships).where(inArray(csrCapabilitySponsorships.id, sponsorshipIds));
  if (requestIds.length) await db().delete(csrSponsorshipRequests).where(inArray(csrSponsorshipRequests.id, requestIds));
  if (csrIds.length) await db().delete(csrBudgets).where(inArray(csrBudgets.csrProfileId, csrIds));
  if (cleanupUserIds.length) await db().delete(userWorkspacePreferences).where(inArray(userWorkspacePreferences.userId, cleanupUserIds));
  if (cleanupUserIds.length) await db().delete(capabilityDecisionNotifications).where(inArray(capabilityDecisionNotifications.userId, cleanupUserIds));
  if (grantIds.length) await db().delete(capabilityAuditRecords).where(inArray(capabilityAuditRecords.grantId, grantIds));
  if (grantIds.length) await db().delete(capabilityGrantFunctions).where(inArray(capabilityGrantFunctions.grantId, grantIds));
  await db().delete(users).where(inArray(users.id, cleanupUserIds)); cleanupUserIds.splice(0);
});

describe("Stage 8 CSR capability workspace isolation", () => {
  it("keeps CSR capability requests and a capability default landing preference bound to one active selected-function grant", async () => {
    const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const applicant = await createPasswordUser({ name: "Stage Eight CSR", email: `stage8-csr-${suffix}@fitizen.test`, passwordHash: "stage8-test-only" }); expect(applicant).toBeTruthy(); cleanupUserIds.push(applicant!.id);
    const admin = await findUserByEmail("admin@fitizen.local"); expect(admin?.role).toBe("admin"); const catalog = (await getCapabilityCatalog()).find(item => item.capability.code === "CSR_SPONSORSHIP"); expect(catalog).toBeTruthy(); const selected = catalog!.functions.filter(item => ["CSR_BRIEF_SUBMIT", "CSR_ASSIGNED_EVENT_VIEW", "CSR_ASSIGNED_PARTICIPANT_VIEW", "CSR_FUNDING_TRACK"].includes(item.code)).map(item => item.id); expect(selected).toHaveLength(4);
    const startsAt = new Date(Date.now() - 86_400_000); const endsAt = new Date(Date.now() + 14 * 86_400_000); const application = await saveCapabilityApplication(applicant!.id, { capabilityId: catalog!.capability.id, functionIds: selected, justification: "I need a controlled CSR sponsorship workspace with selected-function requests, assigned-event visibility, and limited impact evidence for Stage Eight verification.", scopeType: "national", startsAt, endsAt }); await submitCapabilityApplication(applicant!.id, application.id, "Ready for Stage Eight capability review"); const approved = await adminReviewCapabilityApplication(admin!.id, { applicationId: application.id, decision: "approved", note: "Approved for isolated Stage Eight CSR capability verification.", selectedFunctionIds: selected, scope: { scopeType: "national" }, startsAt, endsAt }); const grantId = approved.grant!.id;
    await saveWorkspaceLandingPreference(applicant!.id, { defaultView: "capability", defaultCapabilityGrantId: grantId }); expect(await getWorkspaceLandingPreference(applicant!.id)).toEqual({ defaultView: "capability", defaultCapabilityGrantId: grantId });
    await saveCsrCapabilityProfile(applicant!.id, grantId, { companyName: "Stage Eight Foundation", contactName: "Capability Lead", contactEmail: `lead-${suffix}@fitizen.test` }); const budget = await csrCreateCapabilityBudget(applicant!.id, grantId, { label: "Stage Eight allocation", totalPaise: 200_000 }); const request = await csrSaveCapabilitySponsorshipRequest(applicant!.id, grantId, { budgetId: budget.id, requestKind: "future_event", eventType: "Community fitness camp", intendedAudience: "Community participants", details: "A scoped future community fitness initiative requiring an administrator-created concept before any event exists.", amountPaise: 50_000 }); expect(request.publicId).toMatch(/^CSR-REQ-[A-F0-9]{16}$/);
    const beforeSubmission = await getCsrCapabilityWorkspaceData(applicant!.id, grantId); expect(beforeSubmission?.assignments.map(row => row.request.id)).toEqual([request.id]); await csrSubmitCapabilitySponsorshipRequest(applicant!.id, grantId, request.id, "Submit this independent Stage Eight request for review."); await adminReviewCsrCapabilityRequest(admin!.id, request.id, "approved", "Approved for controlled future-event concept assignment."); const assignment = await adminAssignCsrCapabilityRequest(admin!.id, { requestId: request.id, concept: { title: "Stage Eight Future Fitness Concept", notes: "Planning-only concept. It is not an event and must never accept registrations, QR access, attendance, or health information." }, assignmentNote: "Matches the approved future-event CSR request and keeps event creation with an organizer.", approvedParticipantFields: ["name", "attendanceStatus"] }); expect(assignment.conceptId).toBeTruthy();
    const afterAssignment = await getCsrCapabilityWorkspaceData(applicant!.id, grantId); const assignedRow = afterAssignment?.assignments.find(row => row.request.id === request.id); expect(assignedRow?.sponsorship?.publicId).toMatch(/^CSR-SPN-[A-F0-9]{16}$/); expect(assignedRow?.assignment?.publicId).toMatch(/^CSR-ASN-[A-F0-9]{16}$/); expect(assignedRow?.event).toBeNull(); expect(assignedRow?.concept?.publicId).toMatch(/^CSR-CON-[A-F0-9]{16}$/);
    await expect(adminRecordCsrCapabilityFunding(admin!.id, assignment.sponsorshipId, { transactionReference: "STAGE8-TEST", transactionDate: new Date(), reportSummary: "No real event exists.", complete: false })).rejects.toThrow("real assigned event"); const participants = await getCsrCapabilityAssignedParticipants(applicant!.id, grantId, assignedRow!.assignment!.publicId); expect(participants?.participants).toEqual([]);
  }, 120_000);
});
