import { eq, inArray } from "drizzle-orm";
import { afterEach, describe, expect, it } from "vitest";
import { authorityDeliveryPlans, authorityExceptions, authorityStateProgrammes, capabilityAuditRecords, capabilityDecisionNotifications, capabilityGrantFunctions, capabilityGrants, userAccountProfiles, userWorkspacePreferences, users } from "../../drizzle/schema";
import { adminReviewCapabilityApplication, createAuthorityDeliveryPlan, createAuthorityException, createAuthorityStateProgramme, createPasswordUser, db, findUserByEmail, getActiveCapabilityWorkspaceContext, getAuthorityCapabilityWorkspaceData, getCapabilityCatalog, getSavedWorkspaceDefaultExpiryAlert, resolveAuthorityException, saveCapabilityApplication, saveWorkspaceLandingPreference, submitCapabilityApplication } from "./db";

const cleanupUserIds: number[] = [];

afterEach(async () => {
  if (!cleanupUserIds.length) return;
  const profiles = await db().select().from(userAccountProfiles).where(inArray(userAccountProfiles.userId, cleanupUserIds)); const profileIds = profiles.map(row => row.id); const grants = profileIds.length ? await db().select().from(capabilityGrants).where(inArray(capabilityGrants.userAccountProfileId, profileIds)) : []; const grantIds = grants.map(row => row.id);
  if (grantIds.length) await db().delete(authorityExceptions).where(inArray(authorityExceptions.grantId, grantIds));
  if (grantIds.length) await db().delete(authorityDeliveryPlans).where(inArray(authorityDeliveryPlans.grantId, grantIds));
  if (grantIds.length) await db().delete(authorityStateProgrammes).where(inArray(authorityStateProgrammes.grantId, grantIds));
  if (cleanupUserIds.length) await db().delete(userWorkspacePreferences).where(inArray(userWorkspacePreferences.userId, cleanupUserIds));
  if (cleanupUserIds.length) await db().delete(capabilityDecisionNotifications).where(inArray(capabilityDecisionNotifications.userId, cleanupUserIds));
  if (grantIds.length) await db().delete(capabilityAuditRecords).where(inArray(capabilityAuditRecords.grantId, grantIds));
  if (grantIds.length) await db().delete(capabilityGrantFunctions).where(inArray(capabilityGrantFunctions.grantId, grantIds));
  await db().delete(users).where(inArray(users.id, cleanupUserIds)); cleanupUserIds.splice(0);
});

describe("Stage 9 authority capability workspaces", () => {
  it("keeps district and state records, expiry defaults, exact grants, functions, and scope isolated", async () => {
    const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const applicant = await createPasswordUser({ name: "Stage Nine Authority", email: `stage9-${suffix}@fitizen.test`, passwordHash: "stage9-test-only" }); expect(applicant).toBeTruthy(); cleanupUserIds.push(applicant!.id);
    const admin = await findUserByEmail("admin@fitizen.local"); expect(admin?.role).toBe("admin"); const catalog = await getCapabilityCatalog(); const district = catalog.find(item => item.capability.code === "DISTRICT_LEVEL"); const state = catalog.find(item => item.capability.code === "STATE_LEVEL"); expect(district?.functions.length).toBeGreaterThan(4); expect(state?.functions.length).toBeGreaterThan(5);
    const startsAt = new Date(Date.now() - 60_000); const endsAt = new Date(Date.now() + 5 * 86_400_000); const districtFunctions = district!.functions.filter(item => item.isMandatory || item.code === "DISTRICT_EXCEPTION_MANAGE").map(item => item.id); const application = await saveCapabilityApplication(applicant!.id, { capabilityId: district!.capability.id, functionIds: districtFunctions, justification: "I need an isolated district delivery capability workspace for controlled planning, aggregate monitoring, and scoped exception management verification.", scopeType: "city", city: "Stage Nine City", startsAt, endsAt }); await submitCapabilityApplication(applicant!.id, application.id, "Ready for controlled Stage Nine grant review"); const approved = await adminReviewCapabilityApplication(admin!.id, { applicationId: application.id, decision: "approved", note: "Approved for isolated Stage Nine district verification.", selectedFunctionIds: districtFunctions, scope: { scopeType: "city", city: "Stage Nine City" }, startsAt, endsAt }); const grantId = approved.grant!.id;
    await saveWorkspaceLandingPreference(applicant!.id, { defaultView: "capability", defaultCapabilityGrantId: grantId }); const expiry = await getSavedWorkspaceDefaultExpiryAlert(applicant!.id); expect(expiry).toMatchObject({ grantId, capabilityCode: "DISTRICT_LEVEL" }); expect(expiry!.daysRemaining).toBeLessThanOrEqual(5);
    const plan = await createAuthorityDeliveryPlan(applicant!.id, grantId, { title: "Stage Nine district plan", objective: "Coordinate accountable, scope-bound district delivery for the Stage Nine authority capability verification." }); expect(plan.publicId).toMatch(/^DPL-[A-F0-9]{16}$/);
    const exception = await createAuthorityException(applicant!.id, "DISTRICT_LEVEL", grantId, { title: "Stage Nine delivery exception", details: "Scope-bound delivery exception for controlled Stage Nine resolution and audit verification." }); expect(exception.publicId).toMatch(/^AEX-[A-F0-9]{16}$/); const resolved = await resolveAuthorityException(applicant!.id, "DISTRICT_LEVEL", grantId, exception.id, "Stage Nine evidence reviewed and scoped delivery follow-up completed."); expect(resolved.status).toBe("resolved");
    const districtData = await getAuthorityCapabilityWorkspaceData(applicant!.id, "DISTRICT_LEVEL", grantId); expect(districtData?.plans.map(row => row.id)).toContain(plan.id); expect(districtData?.exceptions.find(row => row.id === exception.id)?.status).toBe("resolved"); await expect(createAuthorityStateProgramme(applicant!.id, grantId, { title: "Wrong workspace programme", objective: "This must never run because the grant belongs to another capability." })).rejects.toThrow("workspace");
    const stateFunctions = state!.functions.filter(item => item.isMandatory).map(item => item.id); const stateApplication = await saveCapabilityApplication(applicant!.id, { capabilityId: state!.capability.id, functionIds: stateFunctions, justification: "I need a separate state programme workspace for controlled Stage Nine programme creation verification.", scopeType: "state", state: "Stage Nine State", startsAt, endsAt }); await submitCapabilityApplication(applicant!.id, stateApplication.id, "Ready for independent Stage Nine state review"); const stateApproved = await adminReviewCapabilityApplication(admin!.id, { applicationId: stateApplication.id, decision: "approved", note: "Approved for isolated Stage Nine state programme verification.", selectedFunctionIds: stateFunctions, scope: { scopeType: "state", state: "Stage Nine State" }, startsAt, endsAt }); const stateGrantId = stateApproved.grant!.id; const programme = await createAuthorityStateProgramme(applicant!.id, stateGrantId, { title: "Stage Nine programme", objective: "A state-scoped programme record that must retain its exact selected function and grant boundary." }); expect(programme.publicId).toMatch(/^STP-[A-F0-9]{16}$/); expect(await getActiveCapabilityWorkspaceContext(applicant!.id, "STATE_LEVEL", stateGrantId)).toBeTruthy();
  }, 80_000);
});
