import Link from "next/link";
import { BadgeIndianRupee, CalendarDays, CircleAlert, CreditCard, Download, FileSpreadsheet, FileText, MapPinned, ShieldCheck, TicketCheck, UsersRound } from "lucide-react";
import { EventModerationControl, MasterControl, MasterControlNote } from "../components/AdminMasterControl";
import AdminAnalytics from "../components/AdminAnalytics";
import AdminVenueDirectory from "../components/AdminVenueDirectory";
import AdminMcdProvisioner from "../components/AdminMcdProvisioner";
import AdminCsrManagement from "../components/AdminCsrManagement";
import AdminCsrProvisioner from "../components/AdminCsrProvisioner";
import AdminStateProvisioner from "../components/AdminStateProvisioner";
import AdminDistrictProvisioner from "../components/AdminDistrictProvisioner";
import AdminDataAuditDashboard from "../components/AdminDataAuditDashboard";
import AdminGatewayFeeSettings from "../components/AdminGatewayFeeSettings";
import AdminShell from "../components/AdminShell";
import { getAdminCsrAssignmentTimeline, getAdminCsrWorkspaceData, getAdminDataAuditData, getAdminWorkspaceData, getPlatformSettings } from "../lib/db";
import { effectiveModerationStatus, moderationLabel } from "../lib/moderation";

const money = (value: number) => `₹${(value / 100).toLocaleString("en-IN")}`;
const readable = (value: string) => value.replaceAll("_", " ");
const userRoleOptions = [{ value: "user", label: "Standard user" }, { value: "mcd", label: "Local Authority" }, { value: "csr", label: "CSR sponsor" }, { value: "state", label: "State Authority" }, { value: "district", label: "District Authority" }, { value: "admin", label: "Administrator" }];
const registrationStatusOptions = [{ value: "confirmed", label: "Confirmed" }, { value: "cancelled", label: "Cancelled" }, { value: "checked_in", label: "Checked in" }];
const paymentStatusOptions = [{ value: "not_required", label: "Not required" }, { value: "pending", label: "Pending" }, { value: "paid", label: "Paid" }, { value: "failed", label: "Failed" }, { value: "refunded", label: "Refunded" }];
const promotionStatusOptions = [{ value: "draft", label: "Draft" }, { value: "scheduled", label: "Scheduled" }, { value: "active", label: "Active" }, { value: "completed", label: "Completed" }];
const views = ["overview", "users", "events", "payments", "venues", "csr", "reports", "settings", "data-audit", "audit"] as const;
const queryDate = (value: string | undefined) => /^\d{4}-\d{2}-\d{2}$/.test(value || "") && !Number.isNaN(new Date(`${value}T00:00:00.000Z`).getTime()) ? new Date(`${value}T00:00:00.000Z`) : null;

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ view?: string; error?: string; updated?: string; auditPaymentStatus?: string; auditFrom?: string; auditTo?: string }> }) {
  const query = await searchParams;
  const view = views.includes(query.view as typeof views[number]) ? query.view as typeof views[number] : "overview";
  const [data, csrData, csrTimeline, settings, dataAudit] = await Promise.all([getAdminWorkspaceData(), getAdminCsrWorkspaceData(), getAdminCsrAssignmentTimeline(), getPlatformSettings(), getAdminDataAuditData({ paymentStatus: query.auditPaymentStatus, from: queryDate(query.auditFrom), to: queryDate(query.auditTo) })]);
  const checkedIn = data.registrations.filter(row => row.registration.status === "checked_in").length;
  const paid = data.registrations.filter(row => row.registration.paymentStatus === "paid").length;
  const totalCapacity = data.tickets.reduce((sum, ticket) => sum + ticket.quantityLimit, 0);
  const totalSold = data.tickets.reduce((sum, ticket) => sum + ticket.quantitySold, 0);
  const activeVenues = data.venues.filter(venue => venue.active); const accessibleVenues = activeVenues.filter(venue => venue.isAccessible); const listedVenueCapacity = activeVenues.reduce((sum, venue) => sum + (venue.capacity || 0), 0);
  const reviewQueue = data.events.filter(row => row.event.moderationStatus === "submitted").slice(0, 5);
  const paymentQueue = data.registrations.filter(row => row.registration.paymentStatus === "pending").slice(0, 5);
  const upcomingEvents = data.events.filter(row => row.event.status === "live" && row.event.startsAt && new Date(row.event.startsAt) >= new Date()).sort((left, right) => Number(new Date(left.event.startsAt!)) - Number(new Date(right.event.startsAt!))).slice(0, 5);
  const statCards = [
    { label: "Platform accounts", value: data.metrics.users, icon: UsersRound },
    { label: "Awaiting approval", value: data.metrics.awaitingApproval, icon: CircleAlert },
    { label: "Live events", value: data.metrics.liveEvents, icon: CalendarDays },
    { label: "Pending payments", value: data.metrics.pendingPayments, icon: CreditCard },
  ];

  return <AdminShell active={view}>
    <div className="dash-page-head">
      <div><span className="eyebrow"><ShieldCheck size={13} /> Guarded master administration</span><h1 className="page-title">{view === "overview" ? "Master Administrator Console" : view === "csr" ? "CSR Sponsorship Governance" : view === "settings" ? "Gateway Fee Settings" : view === "data-audit" ? "Transaction and Role Audit" : `Master ${view[0].toUpperCase()}${view.slice(1)}`}</h1><p>Review submissions, control event availability, assign platform fees, and track the platform through audit-backed operations.</p></div>
      <div className="dash-head-actions"><Link href="/api/exports/admin?format=xlsx" className="btn btn-outline"><FileSpreadsheet size={15} /> XLSX report</Link><Link href="/api/exports/admin?format=pdf" className="btn btn-outline"><FileText size={15} /> PDF report</Link></div>
    </div>
    {query.error ? <div className="error-note" role="alert">{query.error}</div> : null}
    {query.updated ? <div className="notice" role="status">{query.updated}</div> : null}

    {view === "overview" ? <>
      <section className="stats-grid">{statCards.map(({ label, value, icon: Icon }) => <article className="stat-card" key={label}><b>{value.toLocaleString("en-IN")}</b><span><Icon size={14} /> {label}</span></article>)}<article className="stat-card metric-card"><b>{money(data.metrics.totalRevenue)}</b><span><BadgeIndianRupee size={14} /> Gross ticket value</span></article><article className="stat-card metric-card"><b>{money(data.metrics.platformFees)}</b><span><BadgeIndianRupee size={14} /> Platform fees recorded</span></article></section>
      <section className="chart-grid"><article className="panel"><div className="section-head"><div><h3>Approval action centre</h3><p><b>{data.metrics.awaitingApproval}</b> awaiting review · <b>{data.metrics.changesRequested}</b> changes requested.</p></div><Link className="text-button" href="/admin?view=events">Open queue</Link></div>{reviewQueue.length ? <div className="overview-queue">{reviewQueue.map(({ event, organizer }) => <div key={event.id}><span><b>{event.displayName}</b><small>{organizer.name || organizer.email || "Organizer"} · {event.city || "City pending"}</small></span><small>{event.submittedAt ? new Date(event.submittedAt).toLocaleDateString("en-IN") : "Awaiting review"}</small></div>)}</div> : <p className="empty-inline">No events are awaiting approval.</p>}</article><article className="panel"><div className="section-head"><div><h3>Venue directory readiness</h3><p><b>{activeVenues.length}</b> active of {data.venues.length} approved venues · <b>{accessibleVenues.length}</b> marked accessible.</p></div><MapPinned size={20} aria-hidden="true" /></div><div className="overview-mini-stats"><span><b>{listedVenueCapacity.toLocaleString("en-IN")}</b> listed venue capacity</span><span><b>{data.venues.length - activeVenues.length}</b> retired venues</span></div><Link className="btn btn-outline" href="/admin?view=venues">Manage venue directory</Link></article></section>
      <section className="chart-grid"><article className="panel"><div className="section-head"><div><h3>Payment follow-up</h3><p><b>{data.metrics.pendingPayments}</b> booking{data.metrics.pendingPayments === 1 ? "" : "s"} await manual payment confirmation.</p></div><Link className="text-button" href="/admin?view=payments">Open payments</Link></div>{paymentQueue.length ? <div className="overview-queue">{paymentQueue.map(({ registration, attendee, event }) => <div key={registration.id}><span><b>{attendee.name || attendee.email || "Participant"}</b><small>{event.displayName} · {registration.orderNumber}</small></span><small>{money(registration.paidAmountPaise)}</small></div>)}</div> : <p className="empty-inline">No payment confirmations are waiting.</p>}</article><article className="panel"><div className="section-head"><div><h3>Next live events</h3><p>{totalSold} tickets sold across {totalCapacity} available ticket places. {paid} bookings paid · {checkedIn} attendees checked in.</p></div><Link className="text-button" href="/admin?view=reports">Open reports</Link></div>{upcomingEvents.length ? <div className="overview-queue">{upcomingEvents.map(({ event }) => <div key={event.id}><span><b>{event.displayName}</b><small>{event.publicId} · {event.city || "City pending"}</small></span><small>{event.startsAt ? new Date(event.startsAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short" }) : "Date pending"}</small></div>)}</div> : <p className="empty-inline">No upcoming live events are currently scheduled.</p>}</article></section>
      <section className="panel"><div className="section-head"><div><h3>Recent master activity</h3><p>Latest confirmed administrative actions, including event review and venue-directory changes.</p></div><Link className="text-button" href="/admin?view=audit">Open full audit log</Link></div><AuditTable rows={data.audits.slice(0, 8)} /></section>
    </> : null}

    {view === "users" ? <><AdminMcdProvisioner /><AdminCsrProvisioner /><AdminStateProvisioner /><AdminDistrictProvisioner /><section className="panel"><h3>Accounts and master roles</h3><MasterControlNote /><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Account</th><th>Public ID</th><th>Role</th><th>Created</th><th>Guarded action</th></tr></thead><tbody>{data.users.map(user => <tr key={user.id}><td><b>{user.name || "Unnamed account"}</b><br /><small>{user.email || "No email"}</small></td><td>{user.publicId}</td><td><span className={`status-pill ${user.role === "admin" ? "live" : user.role === "mcd" || user.role === "csr" || user.role === "state" || user.role === "district" ? "submitted" : "draft"}`}>{user.role === "mcd" ? "Local Authority" : user.role === "state" ? "State Authority" : user.role === "district" ? "District Authority" : user.role}</span></td><td>{new Date(user.createdAt).toLocaleDateString("en-IN")}</td><td><MasterControl view="users" intent="user-role" targetId={user.id} currentValue={user.role} options={userRoleOptions} /></td></tr>)}</tbody></table></div></section></> : null}

    {view === "events" ? <section className="panel"><div className="section-head"><div><h3>Submission queue and lifecycle control</h3><p>Approve to make an event live. Request changes, freeze, suspend, or remove it with organizer-facing guidance. Set the event platform fee during the same confirmed decision.</p></div><span className="status-pill submitted">{data.metrics.awaitingApproval} awaiting approval</span></div><MasterControlNote /><div className="admin-table-wrap"><table className="admin-table moderation-table"><thead><tr><th>Event</th><th>Organizer</th><th>Moderation</th><th>Platform fee</th><th>Ticket volume</th><th>Guarded decision</th></tr></thead><tbody>{data.events.map(({ event, organizer, category }) => { const eventTickets = data.tickets.filter(ticket => ticket.eventId === event.id); const capacity = eventTickets.reduce((sum, ticket) => sum + ticket.quantityLimit, 0); const sold = eventTickets.reduce((sum, ticket) => sum + ticket.quantitySold, 0); const moderation = effectiveModerationStatus(event); return <tr key={event.id}><td><b>{event.displayName}</b><br /><small>{category?.name || "Uncategorized"} · {event.city || "City pending"}</small>{event.moderationNote ? <small className="table-note">Latest note: {event.moderationNote}</small> : null}</td><td>{organizer.name || organizer.email || `User #${organizer.id}`}</td><td><span className={`status-pill ${moderation}`}>{moderationLabel(moderation)}</span><br /><small>{event.submittedAt ? `Submitted ${new Date(event.submittedAt).toLocaleDateString("en-IN")}` : event.status}</small></td><td><b>{event.platformFeePercent}%</b><br /><small>per paid ticket</small></td><td>{sold} sold / {capacity}</td><td><EventModerationControl targetId={event.id} currentValue={moderation} platformFeePercent={event.platformFeePercent} /></td></tr>; })}</tbody></table></div></section> : null}

    {view === "payments" ? <section className="panel"><h3>Registration and payment operations</h3><MasterControlNote /><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Booking</th><th>Participant</th><th>Event</th><th>Registration</th><th>Payment</th><th>Platform fee</th><th>Master controls</th></tr></thead><tbody>{data.registrations.map(({ registration, attendee, event, ticket }) => <tr key={registration.id}><td><b>{registration.orderNumber}</b><br /><small>Booking reference</small></td><td>{attendee.name || attendee.email || "Participant"}<br /><small>{attendee.publicId}</small></td><td>{event.displayName}<br /><small>{event.publicId} · {ticket?.name || "Ticket pending"}</small></td><td><span className={`status-pill ${registration.status === "checked_in" ? "live" : "draft"}`}>{readable(registration.status)}</span></td><td><span className={`status-pill ${registration.paymentStatus === "paid" ? "live" : "draft"}`}>{readable(registration.paymentStatus)}</span></td><td>{money(registration.platformFeePaise)}</td><td><div className="admin-control-stack"><MasterControl view="payments" intent="registration-status" targetId={registration.id} currentValue={registration.status} options={registrationStatusOptions} /><MasterControl view="payments" intent="payment-status" targetId={registration.id} currentValue={registration.paymentStatus} options={paymentStatusOptions} /></div></td></tr>)}</tbody></table></div></section> : null}

    {view === "venues" ? <AdminVenueDirectory venues={data.venues} reservations={data.venueReservations} requests={data.venueRequests} /> : null}

	    {view === "csr" ? <AdminCsrManagement data={csrData} timeline={csrTimeline} /> : null}

    {view === "settings" ? <AdminGatewayFeeSettings settings={settings} /> : null}

    {view === "data-audit" ? <AdminDataAuditDashboard data={dataAudit} filters={{ paymentStatus: query.auditPaymentStatus, from: query.auditFrom, to: query.auditTo }} /> : null}

    {view === "reports" ? <><section className="stats-grid"><article className="stat-card"><b>{totalCapacity}</b><span>Ticket capacity</span></article><article className="stat-card"><b>{totalSold}</b><span>Tickets sold</span></article><article className="stat-card"><b>{money(data.metrics.totalRevenue)}</b><span>Gross ticket value</span></article><article className="stat-card metric-card"><b>{money(data.metrics.platformFees)}</b><span>Platform fees recorded</span></article></section><section className="panel"><div className="section-head"><div><h3>Interactive activity analytics</h3><p>Switch between registrations, gross ticket value, and platform fees across the last seven calendar days.</p></div><div className="dash-head-actions"><a className="btn btn-outline" href="/api/exports/admin?format=xlsx"><Download size={15} /> XLSX</a><a className="btn btn-outline" href="/api/exports/admin?format=pdf"><Download size={15} /> PDF</a></div></div><AdminAnalytics weeklyActivity={data.weeklyActivity} moderation={{ awaitingApproval: data.metrics.awaitingApproval, changesRequested: data.metrics.changesRequested, liveEvents: data.metrics.liveEvents, events: data.metrics.events }} /></section><section className="panel"><h3>Promotion lifecycle</h3><MasterControlNote /><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Promotion</th><th>Event</th><th>Channel</th><th>Status</th><th>Guarded action</th></tr></thead><tbody>{data.promotions.map(({ promotion, event }) => <tr key={promotion.id}><td><b>{promotion.title}</b></td><td>{event.displayName}</td><td>{promotion.channel}</td><td><span className="status-pill draft">{promotion.status}</span></td><td><MasterControl view="reports" intent="promotion-status" targetId={promotion.id} currentValue={promotion.status} options={promotionStatusOptions} /></td></tr>)}</tbody></table></div></section></> : null}

    {view === "audit" ? <section className="panel"><h3>Administrator audit log</h3><p>Append-only history of all confirmed master changes. Before and after records are retained server-side with every moderation and management action.</p><AuditTable rows={data.audits} full /></section> : null}
  </AdminShell>;
}

function AuditTable({ rows, full = false }: { rows: Awaited<ReturnType<typeof getAdminWorkspaceData>>["audits"]; full?: boolean }) {
  return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>When</th><th>Administrator</th><th>Action</th><th>Entity</th>{full ? <th>Recorded change</th> : null}</tr></thead><tbody>{rows.length ? rows.map(({ audit, admin }) => <tr key={audit.id}><td>{new Date(audit.createdAt).toLocaleString("en-IN")}</td><td>{admin.name || admin.email || `User #${admin.id}`}</td><td>{audit.action}</td><td>{audit.entityType} #{audit.entityId}</td>{full ? <td><small>Before: {JSON.stringify(audit.beforeState)}<br />After: {JSON.stringify(audit.afterState)}</small></td> : null}</tr>) : <tr><td colSpan={full ? 5 : 4}>No master changes have been applied. Audit entries appear only after an administrator submits a confirmed action.</td></tr>}</tbody></table></div>;
}
