import { CalendarClock, Download, FileClock, KeyRound, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { adminCreateCsrMigrationGrantAction, adminCreateLocalAuthorityMigrationGrantAction, adminExpireDueCapabilityGrantsAction, adminReviewCapabilityApplicationAction, adminUpdateCapabilityGrantAction } from "../actions";
import type { getAdminCapabilityGovernanceData, getAdminCapabilityGrantUsageReport } from "../lib/db";
import WorkflowSubmitButton from "./WorkflowSubmitButton";

const readable = (value: string) => value.replaceAll("_", " ");
const dateValue = (value: Date | null) => value ? new Date(value).toISOString().slice(0, 10) : "";
const scopeValue = (row: { scopeType: string; scopeState?: string | null; scopeDistrict?: string | null; scopeCity?: string | null; scopeZone?: string | null; scopeWard?: string | null }) => [readable(row.scopeType), row.scopeState, row.scopeDistrict, row.scopeCity, row.scopeZone, row.scopeWard].filter(Boolean).join(" · ");

function CapabilityReviewFilters({ data }: { data: Awaited<ReturnType<typeof getAdminCapabilityGovernanceData>> }) {
  const filters = data.reviewFilters;
  return <section className="panel capability-search-panel"><div className="section-head"><div><h2>Review queue filters</h2><p>Filter the administrator review queue on the server. Filters affect what is displayed only; they do not change approval authority or MASTER confirmation requirements.</p></div></div><form action="/admin" className="capability-search-form"><input type="hidden" name="view" value="capabilities" /><label><span className="sr-only">Review status</span><select className="select" name="reviewStatus" defaultValue={filters.status || ""}><option value="">All statuses</option><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="changes_requested">Changes requested</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><label><span className="sr-only">Capability</span><select className="select" name="reviewCapability" defaultValue={filters.capability || ""}><option value="">All capabilities</option>{data.catalog.map(item => <option key={item.capability.id} value={item.capability.code}>{item.capability.displayName}</option>)}</select></label><label><span className="sr-only">Applicant</span><input className="input" name="reviewApplicant" defaultValue={filters.applicant || ""} placeholder="Applicant name, email, or public ID" /></label><label><span className="sr-only">Geography</span><input className="input" name="reviewGeography" defaultValue={filters.geography || ""} placeholder="State, district, city, zone, or ward" /></label><label><span className="sr-only">Requested from</span><input className="input" type="date" name="reviewFrom" defaultValue={dateValue(filters.requestedFrom)} /></label><label><span className="sr-only">Requested to</span><input className="input" type="date" name="reviewTo" defaultValue={dateValue(filters.requestedTo)} /></label><button className="btn btn-outline" type="submit">Apply review filters</button><Link className="text-button" href="/admin?view=capabilities">Clear filters</Link></form><p className="empty-inline">Showing {data.applications.length} matching application{data.applications.length === 1 ? "" : "s"}.</p></section>;
}

function ApplicationEvidence({ application, documents }: { application: { justification: string; applicantNote: string | null; roleSpecificData: unknown }; documents: Array<{ id: number; storageKey: string; fileName: string; contentType: string; sizeBytes: number }> }) {
  const details = application.roleSpecificData && typeof application.roleSpecificData === "object" && !Array.isArray(application.roleSpecificData) ? Object.entries(application.roleSpecificData as Record<string, unknown>).filter(([, value]) => typeof value === "string" && value) : [];
  return <><span>{application.justification}</span>{application.applicantNote ? <small className="table-note">Note: {application.applicantNote}</small> : null}{details.length ? <details className="table-note"><summary>Role-specific application details</summary><dl>{details.map(([key, value]) => <div key={key}><dt>{readable(key.replace(/([A-Z])/g, "_$1").toLowerCase())}</dt><dd>{String(value)}</dd></div>)}</dl></details> : null}{documents.length ? <small className="table-note">Documents: {documents.map(document => <a key={document.id} href={`/manus-storage/${document.storageKey}`} target="_blank" rel="noreferrer">{document.fileName} ({Math.ceil(document.sizeBytes / 1024)} KB)</a>).map((item, index) => <span key={index}>{index ? ", " : ""}{item}</span>)}</small> : null}</>;
}

export default function AdminCapabilityManagement({ data, grantUsage }: { data: Awaited<ReturnType<typeof getAdminCapabilityGovernanceData>>; grantUsage: Awaited<ReturnType<typeof getAdminCapabilityGrantUsageReport>> }) {
  const localAuthority = data.catalog.find(item => item.capability.code === "LOCAL_AUTHORITY");

  const csr = data.catalog.find(item => item.capability.code === "CSR_SPONSORSHIP");
	  return <div className="capability-governance"><section className="stats-grid"><article className="stat-card"><b>{data.metrics.activeCatalog}</b><span><KeyRound size={14} /> Active capabilities</span></article><article className="stat-card"><b>{data.metrics.submitted}</b><span><FileClock size={14} /> Applications awaiting review</span></article><article className="stat-card metric-card"><b>{data.metrics.activeGrants}</b><span><ShieldCheck size={14} /> Active time-bound grants</span></article><article className={`stat-card ${data.metrics.dueForExpiry ? "attention" : ""}`}><b>{data.metrics.dueForExpiry}</b><span><CalendarClock size={14} /> Due for expiry</span></article></section><CapabilityReviewFilters data={data} />
    <section className="panel"><div className="section-head"><div><span className="eyebrow"><KeyRound size={13} /> Capability catalog</span><h2>Available capabilities and functions</h2><p>Catalog entries are searchable by applicants. Required/optional functions, dependencies, and sensitive-data declarations are informational in Stage 3; Stage 4 will enforce authorized functions server-side.</p></div></div><div className="capability-catalog-grid admin-capability-catalog">{data.catalog.map(({ capability, functions }) => <article className="capability-card" key={capability.id}><span className={`status-pill ${capability.active ? "live" : "draft"}`}>{capability.active ? "Active" : "Inactive"}</span><h3>{capability.displayName}</h3><p>{capability.description}</p><small>Audience: {capability.audience}</small><div className="capability-function-list">{functions.map(fn => <div key={fn.id}><b>{fn.displayName} <small>{fn.isMandatory ? "Required" : "Optional"}{fn.handlesSensitiveData ? " · Sensitive data" : ""}</small></b><small>{fn.code}</small>{fn.dependencyCodes?.length ? <small>Depends on: {fn.dependencyCodes.join(", ")}</small> : null}</div>)}</div></article>)}</div></section>
	    <section className="panel"><div className="section-head"><div><h2>Capability application review</h2><p>Review only submitted applications. MASTER confirmation records returned, rejected, or approved decisions; approval issues one time-bound scoped grant using only applicant-selected functions.</p></div><span className="status-pill submitted">{data.metrics.submitted} awaiting review</span></div><div className="admin-table-wrap"><table className="admin-table capability-admin-table"><thead><tr><th>Applicant</th><th>Capability and requested functions</th><th>Scope and requested validity</th><th>Applicant evidence</th><th>Master decision</th></tr></thead><tbody>{data.applications.length ? data.applications.map(row => <tr key={row.application.id}><td><b>{row.user.name || "Account holder"}</b><br /><small>{row.user.email || row.user.publicId}</small><br /><small>{row.profile.profileTerminology}</small></td><td><b>{row.capability.displayName}</b><br /><small>{row.functions.map(fn => fn.displayName).join(", ") || "No requested functions"}</small></td><td>{scopeValue({ scopeType: row.application.requestedScopeType, scopeState: row.application.requestedState, scopeDistrict: row.application.requestedDistrict, scopeCity: row.application.requestedCity, scopeZone: row.application.requestedZone, scopeWard: row.application.requestedWard })}<br /><small>{dateValue(row.application.requestedStartsAt)} to {dateValue(row.application.requestedEndsAt)}</small></td><td><ApplicationEvidence application={row.application} documents={row.documents} /><br /><span className={`status-pill ${row.application.status === "submitted" ? "submitted" : row.application.status === "approved" ? "live" : row.application.status === "changes_requested" ? "attention" : row.application.status === "rejected" ? "critical" : "draft"}`}>{readable(row.application.status)}</span>{row.application.adminNote ? <small className="table-note">Decision: {row.application.adminNote}</small> : null}</td><td>{row.application.status === "submitted" ? <CapabilityReviewControl application={row.application} functions={row.functions} /> : <small>Decision already recorded</small>}</td></tr>) : <tr><td colSpan={5}>No capability applications have been created.</td></tr>}</tbody></table></div></section>
    {localAuthority && data.localAuthorityAccounts.length ? <section className="panel"><div className="section-head"><div><h2>Stage 4 Local Authority migration grants</h2><p>Prepare a current Local Authority account for the first grant-enforced function. This creates a selected-function, time-bound, scoped grant without changing its retained `mcd` role. Enable enforcement only through the rollout flag after scope review.</p></div><ShieldCheck size={20} aria-hidden="true" /></div>{data.localAuthorityAccounts.map(account => <LocalAuthorityMigrationGrantControl key={account.user.id} account={account.user} functions={localAuthority.functions} />)}</section> : null}
    {csr && data.csrAccounts.length ? <section className="panel"><div className="section-head"><div><h2>Stage 5 CSR migration grants</h2><p>Prepare an existing CSR sponsor for the selective brief-submission and impact-export cutover without changing the retained `csr` role. Use national scope when granting selected sponsor-wide impact export.</p></div><ShieldCheck size={20} aria-hidden="true" /></div>{data.csrAccounts.map(account => <CsrMigrationGrantControl key={account.user.id} account={account.user} functions={csr.functions} />)}</section> : null}
    <section className="panel"><div className="section-head"><div><h2>Grant expiry operations</h2><p>{data.metrics.dueForExpiry ? `${data.metrics.dueForExpiry} active grant${data.metrics.dueForExpiry === 1 ? " is" : "s are"} past its end date. Process the queue to persist the expired status and both audit records.` : "No active grants are past their end date. Effective authorization already treats expired dates as inactive."}</p></div><CalendarClock size={20} aria-hidden="true" /></div>{data.metrics.dueForExpiry ? <form action={adminExpireDueCapabilityGrantsAction} className="admin-control-stack capability-grant-status-control"><textarea className="input" name="administrativeReason" rows={2} required minLength={4} placeholder="Reason for this expiry batch" /><div className="admin-confirm"><input className="input" name="confirmation" required placeholder="Type MASTER" /><WorkflowSubmitButton className="btn btn-outline" pendingLabel="Expiring grants…">Process due expiries</WorkflowSubmitButton></div></form> : <p className="empty-inline">Expiry processing is ready when an active grant reaches its end date.</p>}</section>
	    <section className="panel"><div className="section-head"><div><h2>Time-bound scoped grants</h2><p>Manage grant lifecycle states with a reason and MASTER confirmation. Stage 4 applies selected-function grant checks to the first Local Authority execution path only when enforcement is enabled.</p></div><CalendarClock size={20} aria-hidden="true" /></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Account</th><th>Grant</th><th>Functions</th><th>Scope and validity</th><th>Active status</th><th>Guarded update</th></tr></thead><tbody>{data.grants.length ? data.grants.map(row => <tr key={row.grant.id}><td><b>{row.user.name || "Account holder"}</b><br /><small>{row.user.email || row.user.publicId}</small></td><td><b>{row.capability.displayName}</b><br /><small>{row.grant.administrativeReason}</small></td><td>{row.functions.map(fn => fn.displayName).join(", ")}</td><td>{scopeValue({ scopeType: row.grant.scopeType, scopeState: row.grant.scopeState, scopeDistrict: row.grant.scopeDistrict, scopeCity: row.grant.scopeCity, scopeZone: row.grant.scopeZone, scopeWard: row.grant.scopeWard })}<br /><small>{dateValue(row.grant.startsAt)} to {dateValue(row.grant.endsAt)}</small></td><td><span className={`status-pill ${row.effectiveStatus === "active" ? "live" : row.effectiveStatus === "scheduled" ? "submitted" : row.effectiveStatus === "suspended" ? "attention" : "critical"}`}>{readable(row.effectiveStatus)}</span></td><td><CapabilityGrantStatusControl grantId={row.grant.id} currentStatus={row.grant.status} /></td></tr>) : <tr><td colSpan={6}>No capability grants have been issued.</td></tr>}</tbody></table></div></section>
	    <section className="panel"><div className="section-head"><div><h2>Grant usage reporting</h2><p>Current permission state, selected functions, and the latest recorded activity provide an auditable view without changing authorization decisions.</p></div><div className="dash-head-actions"><Link className="btn btn-outline" href="/api/exports/csr-grant-usage?format=csv"><Download size={15} /> CSR usage CSV</Link><Link className="btn btn-outline" href="/api/exports/csr-grant-usage?format=xlsx"><Download size={15} /> CSR usage XLSX</Link></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Account and grant</th><th>Selected functions</th><th>Usage evidence</th><th>Permission management</th></tr></thead><tbody>{grantUsage.length ? grantUsage.map(row => <tr key={row.grant.id}><td><b>{row.user.name || "Account holder"}</b><br /><small>{row.capability.displayName} · Grant #{row.grant.id}</small><br /><span className={`status-pill ${row.effectiveStatus === "active" ? "live" : row.effectiveStatus === "scheduled" ? "submitted" : row.effectiveStatus === "suspended" ? "attention" : "critical"}`}>{readable(row.effectiveStatus)}</span></td><td>{row.functions.map(item => item.displayName).join(", ") || "No active selected functions"}</td><td><b>{row.usageCount}</b> authorized action{row.usageCount === 1 ? "" : "s"}<br /><small>{row.lastActivity ? `${readable(row.lastActivity.action)} · ${new Date(row.lastActivity.createdAt).toLocaleString("en-IN")}` : "No execution evidence recorded"}</small></td><td><CapabilityGrantStatusControl grantId={row.grant.id} currentStatus={row.grant.status} /></td></tr>) : <tr><td colSpan={4}>No capability grants are available for usage reporting.</td></tr>}</tbody></table></div></section>
    <section className="panel"><div className="section-head"><div><h2>Capability audit evidence</h2><p>Append-only capability application and grant records. Historic platform audit entries remain unchanged.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>When</th><th>Actor ID</th><th>Action</th><th>Application</th><th>Grant</th></tr></thead><tbody>{data.audits.length ? data.audits.map(audit => <tr key={audit.id}><td>{new Date(audit.createdAt).toLocaleString("en-IN")}</td><td>{audit.actorUserId}</td><td>{audit.action}</td><td>{audit.applicationId || "—"}</td><td>{audit.grantId || "—"}</td></tr>) : <tr><td colSpan={5}>Capability audit records will appear when an application or grant action occurs.</td></tr>}</tbody></table></div></section>
  </div>;
}

function CapabilityReviewControl({ application, functions }: { application: { id: number; requestedScopeType: "national" | "state" | "district" | "city" | "zone" | "ward"; requestedState: string | null; requestedDistrict: string | null; requestedCity: string | null; requestedZone: string | null; requestedWard: string | null; requestedStartsAt: Date | null; requestedEndsAt: Date | null }; functions: Array<{ id: number; displayName: string; description: string; isMandatory: boolean }> }) {
  return <form action={adminReviewCapabilityApplicationAction} className="admin-control-stack capability-review-control"><input type="hidden" name="applicationId" value={application.id} /><label className="sr-only" htmlFor={`cap-decision-${application.id}`}>Decision</label><select className="select" id={`cap-decision-${application.id}`} name="decision" defaultValue="approved"><option value="approved">Approve and issue grant</option><option value="changes_requested">Request additions</option><option value="rejected">Reject application</option></select><fieldset><legend>Grant only requested functions</legend>{functions.map(fn => <label className="capability-inline-check" key={fn.id}><input type="checkbox" name="functionIds" value={fn.id} defaultChecked required={fn.isMandatory} /><span>{fn.displayName}{fn.isMandatory ? " (required)" : ""}</span></label>)}</fieldset><div className="capability-scope-grid"><select className="select" name="scopeType" defaultValue={application.requestedScopeType}><option value="national">National</option><option value="state">State</option><option value="district">District</option><option value="city">City</option><option value="zone">Zone</option><option value="ward">Ward</option></select><input className="input" name="scopeState" placeholder="State" defaultValue={application.requestedState || ""} /><input className="input" name="scopeDistrict" placeholder="District" defaultValue={application.requestedDistrict || ""} /><input className="input" name="scopeCity" placeholder="City" defaultValue={application.requestedCity || ""} /><input className="input" name="scopeZone" placeholder="Zone" defaultValue={application.requestedZone || ""} /><input className="input" name="scopeWard" placeholder="Ward" defaultValue={application.requestedWard || ""} /><input className="input" name="startsAt" type="date" defaultValue={dateValue(application.requestedStartsAt)} /><input className="input" name="endsAt" type="date" defaultValue={dateValue(application.requestedEndsAt)} /></div><textarea className="input" name="reviewNote" rows={3} placeholder="Required for returned or rejected applications; recorded for approved grants." /><div className="admin-confirm"><input className="input" name="confirmation" required placeholder="Type MASTER" /><WorkflowSubmitButton className="btn btn-outline" pendingLabel="Recording…">Record decision</WorkflowSubmitButton></div></form>;
}

function CapabilityGrantStatusControl({ grantId, currentStatus }: { grantId: number; currentStatus: "active" | "suspended" | "revoked" | "expired" }) {
  return <form action={adminUpdateCapabilityGrantAction} className="admin-control-stack capability-grant-status-control"><input type="hidden" name="grantId" value={grantId} /><select className="select" name="status" defaultValue={currentStatus}><option value="active">Active</option><option value="suspended">Suspend</option><option value="revoked">Revoke</option><option value="expired">Mark expired</option></select><textarea className="input" name="administrativeReason" rows={2} required minLength={4} placeholder="Reason for grant status change" /><div className="admin-confirm"><input className="input" name="confirmation" required placeholder="Type MASTER" /><WorkflowSubmitButton className="btn btn-outline" pendingLabel="Updating…">Update grant</WorkflowSubmitButton></div></form>;
}

function LocalAuthorityMigrationGrantControl({ account, functions }: { account: { id: number; name: string | null; email: string | null; publicId: string }; functions: Array<{ id: number; displayName: string; isMandatory: boolean; handlesSensitiveData: boolean }> }) {
  return <form action={adminCreateLocalAuthorityMigrationGrantAction} className="admin-control-stack capability-review-control"><input type="hidden" name="userId" value={account.id} /><p><b>{account.name || "Local Authority account"}</b> <small>{account.email || account.publicId}</small></p><fieldset><legend>Grant functions for the first migration path</legend>{functions.map(fn => <label className="capability-inline-check" key={fn.id}><input type="checkbox" name="functionIds" value={fn.id} defaultChecked required={fn.isMandatory} /><span>{fn.displayName}{fn.isMandatory ? " (required)" : ""}{fn.handlesSensitiveData ? " · sensitive data" : ""}</span></label>)}</fieldset><div className="capability-scope-grid"><select className="select" name="scopeType" defaultValue="national"><option value="national">National</option><option value="state">State</option><option value="district">District</option><option value="city">City</option><option value="zone">Zone</option><option value="ward">Ward</option></select><input className="input" name="scopeState" placeholder="State" /><input className="input" name="scopeDistrict" placeholder="District" /><input className="input" name="scopeCity" placeholder="City" /><input className="input" name="scopeZone" placeholder="Zone" /><input className="input" name="scopeWard" placeholder="Ward" /><input className="input" name="startsAt" type="date" required /><input className="input" name="endsAt" type="date" required /></div><textarea className="input" name="administrativeReason" rows={2} required minLength={4} placeholder="Reason for staged migration grant" /><div className="admin-confirm"><input className="input" name="confirmation" required placeholder="Type MASTER" /><WorkflowSubmitButton className="btn btn-outline" pendingLabel="Granting…">Create migration grant</WorkflowSubmitButton></div></form>;
}

function CsrMigrationGrantControl({ account, functions }: { account: { id: number; name: string | null; email: string | null; publicId: string }; functions: Array<{ id: number; displayName: string; isMandatory: boolean; handlesSensitiveData: boolean }> }) {
  return <form action={adminCreateCsrMigrationGrantAction} className="admin-control-stack capability-review-control"><input type="hidden" name="userId" value={account.id} /><p><b>{account.name || "CSR sponsor account"}</b> <small>{account.email || account.publicId}</small></p><fieldset><legend>Grant selected CSR migration functions</legend>{functions.map(fn => <label className="capability-inline-check" key={fn.id}><input type="checkbox" name="functionIds" value={fn.id} defaultChecked={fn.isMandatory} required={fn.isMandatory} /><span>{fn.displayName}{fn.isMandatory ? " (required)" : ""}{fn.handlesSensitiveData ? " · sensitive data" : ""}</span></label>)}</fieldset><div className="capability-scope-grid"><select className="select" name="scopeType" defaultValue="national"><option value="national">National</option><option value="state">State</option><option value="district">District</option><option value="city">City</option><option value="zone">Zone</option><option value="ward">Ward</option></select><input className="input" name="scopeState" placeholder="State" /><input className="input" name="scopeDistrict" placeholder="District" /><input className="input" name="scopeCity" placeholder="City" /><input className="input" name="scopeZone" placeholder="Zone" /><input className="input" name="scopeWard" placeholder="Ward" /><input className="input" name="startsAt" type="date" required /><input className="input" name="endsAt" type="date" required /></div><textarea className="input" name="administrativeReason" rows={2} required minLength={4} placeholder="Reason for staged CSR migration grant" /><div className="admin-confirm"><input className="input" name="confirmation" required placeholder="Type MASTER" /><WorkflowSubmitButton className="btn btn-outline" pendingLabel="Granting…">Create CSR migration grant</WorkflowSubmitButton></div></form>;
}
