"use client";

import { Activity, BarChart3, ShieldCheck } from "lucide-react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Analytics = { totalEntries: number; byDate: { date: string; count: number }[]; byWellbeing: { label: string; count: number }[] };
const palette = ["#0e7c66", "#e5a13c", "#f65f4a", "#7d5ac7", "#2777b8"];

export default function AuthorityHealthAnalytics({ analytics, capabilityCode, grantId }: { analytics: Analytics; capabilityCode: string; grantId: number }) {
  return <section className="panel"><div className="section-head"><div><span className="eyebrow"><Activity size={13} /> Aggregate health history</span><h2>Scoped wellbeing activity</h2><p>Only aggregated event-day counts appear. This view never includes a participant identity, entry text, correction text, or individual health record.</p></div><div className="split-actions"><a className="btn btn-outline" href={`/api/exports/authority-health?capability=${capabilityCode}&grant=${grantId}`}>Download aggregate CSV</a><ShieldCheck size={20} /></div></div><section className="stats-grid"><article className="stat-card"><b>{analytics.totalEntries}</b><span>Scoped health entries</span></article><article className="stat-card"><b>{analytics.byDate.length}</b><span>Days with entries</span></article><article className="stat-card"><b>{analytics.byWellbeing.length}</b><span>Aggregate status groups</span></article></section>{analytics.totalEntries ? <div className="analytics-grid"><div className="summary-box"><b><BarChart3 size={15} /> Entries by day</b><div className="chart-frame"><ResponsiveContainer width="100%" height={220}><BarChart data={analytics.byDate}><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} /><Bar dataKey="count" fill="#0e7c66" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></div><div className="summary-box"><b>Wellbeing status distribution</b><div className="chart-frame"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={analytics.byWellbeing} dataKey="count" nameKey="label" innerRadius={46} outerRadius={80} paddingAngle={3}>{analytics.byWellbeing.map((item, index) => <Cell key={item.label} fill={palette[index % palette.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></div></div> : <div className="empty-card"><h3>No scoped health check-ins yet</h3><p>Aggregate charts populate only after consented participants submit check-ins for events inside this grant territory.</p></div>}</section>;
}
