import { BellRing, CheckCheck, CheckCircle2, Filter, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { markCapabilityDecisionNotificationReadAction, markCapabilityDecisionNotificationsReadAction } from "../actions";
import type { CapabilityDecisionNotificationFilter, getCapabilityDecisionNotifications } from "../lib/db";
import styles from "./CapabilityDecisionInbox.module.css";

type Notification = Awaited<ReturnType<typeof getCapabilityDecisionNotifications>>[number];

const filters: Array<{ value: CapabilityDecisionNotificationFilter; label: string }> = [{ value: "all", label: "All outcomes" }, { value: "unread", label: "Unread only" }, { value: "approved", label: "Approved applications" }, { value: "returned", label: "Returned for revision" }, { value: "rejected", label: "Rejected applications" }, { value: "grant", label: "Grant updates" }];

export default function CapabilityDecisionInbox({ notifications, filter, unreadCount }: { notifications: Notification[]; filter: CapabilityDecisionNotificationFilter; unreadCount: number }) {
  const unread = notifications.filter(notification => !notification.readAt);
  if (!unreadCount && !notifications.length) return null;
  return <section className={`panel ${styles.inbox}`} id="capability-decision-notifications" aria-labelledby="capability-decision-title"><div className="section-head"><div><span className="eyebrow"><BellRing size={13} /> Capability decisions <span className={styles.badge} aria-label={`${unreadCount} unread decision notifications`}>{unreadCount}</span></span><h2 id="capability-decision-title">{unreadCount ? `${unreadCount} decision${unreadCount === 1 ? "" : "s"} needs your attention` : "Decision history"}</h2><p>These private in-app updates record administrator application and grant decisions. Your applications and grants below remain the authoritative record.</p></div><ShieldCheck size={21} aria-hidden="true" /></div><div className={styles.controls}><form action="/dashboard/capabilities" className={styles.filterForm}><label><Filter size={14} aria-hidden="true" /><span className="sr-only">Filter decision outcomes</span><select className="select" name="decisionFilter" defaultValue={filter}>{filters.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button type="submit" className="btn btn-outline btn-small">Filter outcomes</button></form>{unread.length ? <form action={markCapabilityDecisionNotificationsReadAction}><input type="hidden" name="decisionFilter" value={filter} /><button type="submit" className={`btn btn-outline btn-small ${styles.bulkButton}`}><CheckCheck size={15} /> Mark matching unread as read</button></form> : null}</div>{notifications.length ? <div className={styles.list}>{notifications.map(notification => <article className={`${styles.item} ${notification.readAt ? styles.read : ""}`} key={notification.id}><div className={styles.copy}><span><CheckCircle2 size={16} aria-hidden="true" /><b>{notification.title}</b>{!notification.readAt ? <i className={styles.unreadDot} aria-label="Unread" /> : null}</span><p>{notification.body}</p><small>{new Date(notification.createdAt).toLocaleString("en-IN")}</small></div><div className={styles.actions}><Link className="btn btn-outline btn-small" href={notification.actionUrl}>Review details</Link>{!notification.readAt ? <form action={markCapabilityDecisionNotificationReadAction}><input type="hidden" name="notificationId" value={notification.id} /><button type="submit" className={styles.markRead}>Mark read</button></form> : <span className={styles.readLabel}>Read</span>}</div></article>)}</div> : <p className={styles.empty}>No decision notices match this outcome filter. Try another filter to review your private decision history.</p>}</section>;
}
