"use client";

import { Check, Crop, RotateCcw } from "lucide-react";
import { useEffect, useRef, useState } from "react";

export default function CoverCropper({ file, onApply, onCancel }: { file: File; onApply: (file: File) => void; onCancel: () => void }) {
  const [zoom, setZoom] = useState(1); const [x, setX] = useState(0); const [y, setY] = useState(0); const [preview, setPreview] = useState(""); const source = useRef<HTMLImageElement | null>(null);
  useEffect(() => { const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url); }, [file]);
  const apply = () => { const image = source.current; if (!image) return; const canvas = document.createElement("canvas"); canvas.width = 1920; canvas.height = 1080; const ctx = canvas.getContext("2d"); if (!ctx) return; const scale = Math.max(canvas.width / image.naturalWidth, canvas.height / image.naturalHeight) * zoom; const width = image.naturalWidth * scale; const height = image.naturalHeight * scale; const left = (canvas.width - width) / 2 + x * canvas.width; const top = (canvas.height - height) / 2 + y * canvas.height; ctx.drawImage(image, left, top, width, height); canvas.toBlob(blob => { if (blob) onApply(new File([blob], `${file.name.replace(/\.[^.]+$/, "")}-cover.webp`, { type: "image/webp" })); }, "image/webp", 0.9); };
  return <div className="cropper"><div className="crop-stage"><img ref={source} src={preview} alt="Crop source" style={{ transform: `translate(${x * 100}%, ${y * 100}%) scale(${zoom})` }} /></div><div className="crop-head"><span><Crop size={15} /> Adjust 16:9 crop</span><button type="button" className="icon-button" aria-label="Reset crop" onClick={() => { setZoom(1); setX(0); setY(0); }}><RotateCcw size={15} /></button></div><label className="form-label">Zoom<input type="range" min="1" max="2.4" step="0.05" value={zoom} onChange={event => setZoom(Number(event.target.value))} /></label><div className="two-col"><label className="form-label">Horizontal position<input type="range" min="-0.5" max="0.5" step="0.02" value={x} onChange={event => setX(Number(event.target.value))} /></label><label className="form-label">Vertical position<input type="range" min="-0.5" max="0.5" step="0.02" value={y} onChange={event => setY(Number(event.target.value))} /></label></div><div className="crop-actions"><button type="button" className="btn btn-outline" onClick={onCancel}>Choose another image</button><button type="button" className="btn btn-coral" onClick={apply}><Check size={15} /> Apply crop</button></div></div>;
}
