"use client";

import { ImageUp, Sparkles } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { validateEventBanner } from "../lib/event-banner";
import CoverCropper from "./CoverCropper";

export default function CoverUpload({ initialUrl }: { initialUrl: string | null }) {
  const inputRef = useRef<HTMLInputElement>(null); const [cropSource, setCropSource] = useState<File | null>(null); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [preview, setPreview] = useState(initialUrl || ""); const [dragging, setDragging] = useState(false); const [status, setStatus] = useState(initialUrl ? "Current banner retained until you choose a replacement." : "Choose or drop an image to begin.");
  useEffect(() => { if (!selectedFile) { setPreview(initialUrl || ""); return; } const url = URL.createObjectURL(selectedFile); setPreview(url); return () => URL.revokeObjectURL(url); }, [initialUrl, selectedFile]);
  const queueCrop = (file: File | undefined) => { if (!file) return; const error = validateEventBanner(file.type, file.size); if (error) { setStatus(error); return; } setCropSource(file); setStatus("Adjust the 16:9 crop, then apply it to attach the banner."); };
  const handleInput = (event: React.ChangeEvent<HTMLInputElement>) => { queueCrop(event.target.files?.[0]); event.currentTarget.value = ""; };
  const applyCrop = (file: File) => { const input = inputRef.current; if (!input) return; const transfer = new DataTransfer(); transfer.items.add(file); input.files = transfer.files; setSelectedFile(file); setCropSource(null); setStatus("Cropped banner ready. Click Save and Next to upload it securely."); };
  return <div className="cover-upload"><div className="banner-upload-head"><Sparkles size={17} aria-hidden="true" /><div><b>Event banner</b><span>Used across your listing and public event page.</span></div></div><div className="cover-preview">{preview ? <img src={preview} alt="Event banner preview" /> : <span>Event banner preview</span>}</div><div className={`upload-dropzone ${dragging ? "dragging" : ""}`} role="button" tabIndex={0} aria-label="Choose or drop an event banner image" onDragEnter={event => { event.preventDefault(); setDragging(true); }} onDragOver={event => event.preventDefault()} onDragLeave={event => { event.preventDefault(); setDragging(false); }} onDrop={event => { event.preventDefault(); setDragging(false); queueCrop(event.dataTransfer.files?.[0]); }} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); inputRef.current?.click(); } }}><ImageUp size={22} aria-hidden="true" /><b>{dragging ? "Drop banner image to crop" : "Drag and drop a banner image"}</b><span>or choose a JPEG, PNG, or WebP file</span><input ref={inputRef} name="coverFile" className="upload-file-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={handleInput} /></div>{cropSource ? <CoverCropper file={cropSource} onCancel={() => { setCropSource(null); setStatus("Banner selection cancelled. Choose or drop another image."); }} onApply={applyCrop} /> : null}<p role="status" aria-live="polite" className="cover-guidance">{status} JPEG, PNG, or WebP up to 5 MB. Recommended: 1920 × 1080 px (16:9).</p></div>;
}
