import { MapPin, Search, SlidersHorizontal } from "lucide-react";

type DiscoveryParams = { search?: string; city?: string; category?: string; filter?: string; sort?: string; accessible?: string };
type Category = { id: number; name: string; slug: string };

export function DiscoveryForm({ params, categories }: { params: DiscoveryParams; categories: Category[] }) {
  const hasAppliedFilters = Boolean(params.search || params.city || params.category || params.filter || params.accessible || (params.sort && params.sort !== "soonest"));
  return <form method="get" action="/" className="home-discovery" aria-label="Find events"><div className="search-panel"><label className="field-inline"><span className="sr-only">Search events, interests, or activities</span><Search size={18} aria-hidden="true" /><input name="search" defaultValue={params.search || ""} aria-label="Search events, interests, or activities" placeholder="Search for events, interests or activities" /></label><label className="field-inline"><span className="sr-only">Choose city</span><MapPin size={17} aria-hidden="true" /><select name="city" aria-label="Choose city" defaultValue={params.city || ""}><option value="">All cities</option><option value="Bengaluru">Bengaluru</option><option value="Delhi NCR">Delhi NCR</option><option value="Mumbai">Mumbai</option><option value="Hyderabad">Hyderabad</option><option value="Pune">Pune</option></select></label><button className="btn btn-coral" type="submit">Find events</button></div><div className="discovery-controls" aria-label="Refine events"><SlidersHorizontal size={16} aria-hidden="true" /><select name="category" aria-label="Filter by category" defaultValue={params.category || ""}><option value="">All categories</option>{categories.map(category => <option key={category.id} value={category.slug}>{category.name}</option>)}</select><select name="filter" aria-label="Filter by date or price" defaultValue={params.filter || ""}><option value="">Any date or price</option><option value="This Weekend">This Weekend</option><option value="This Week">This Week</option><option value="This Month">This Month</option><option value="Tomorrow">Tomorrow</option><option value="Today">Today</option><option value="Free">Free</option><option value="Paid">Paid</option></select><select name="sort" aria-label="Sort events" defaultValue={params.sort || "soonest"}><option value="soonest">Soonest first</option><option value="latest">Latest first</option><option value="recent">Recently added</option></select><label className="choice discovery-accessible"><input name="accessible" value="1" type="checkbox" defaultChecked={params.accessible === "1"} /><span>Accessible venues</span></label><button className="text-button" type="submit">Apply</button>{hasAppliedFilters ? <a className="text-button" href="/">Clear</a> : null}</div></form>;
}

export function DiscoveryQuickFilters({ activeFilter, sort, filters, params }: { activeFilter?: string; sort: string; filters: string[]; params: DiscoveryParams }) {
  return <div className="quick-row"><strong>Quickly filter events by</strong>{filters.map(filter => { const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value && key !== "filter") query.set(key, value); }); query.set("filter", filter); query.set("sort", sort || "soonest"); const href = `/?${query.toString()}`; return <a key={filter} href={href} className={`filter-chip ${activeFilter === filter ? "active" : ""}`} aria-current={activeFilter === filter ? "page" : undefined}>{filter}</a>; })}</div>;
}

export function DiscoveryResults({ children }: { children: React.ReactNode }) { return <>{children}</>; }
