import { Activity, BookOpen, HeartHandshake, PencilLine, ShieldCheck, Sparkles } from "lucide-react";
import { createParticipantHistoryCorrectionAction, createParticipantHistoryEntryAction, setParticipantHealthConsentAction } from "../actions";
import type { getParticipantHistoryWorkspace } from "../lib/db";

type WorkspaceData = Awaited<ReturnType<typeof getParticipantHistoryWorkspace>>;

function datesBetween(startDate: string | null, endDate: string | null) {
  if (!startDate || !endDate) return []; const dates: string[] = []; const current = new Date(`${startDate}T12:00:00Z`); const end = new Date(`${endDate}T12:00:00Z`); while (current <= end && dates.length < 31) { dates.push(current.toISOString().slice(0, 10)); current.setUTCDate(current.getUTCDate() + 1); } return dates;
}
function EntryFields({ entryType }: { entryType: "health" | "education" | "community" | "experience" }) {
  if (entryType === "health") return <><label>How are you feeling?<select className="input" name="wellbeing" required defaultValue=""><option value="" disabled>Select wellbeing</option><option value="great">Great</option><option value="good">Good</option><option value="okay">Okay</option><option value="low">Low</option></select></label><label>Energy level<select className="input" name="energyLevel" required defaultValue=""><option value="" disabled>Select 1–5</option>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>Participation comfort<select className="input" name="comfort" required defaultValue=""><option value="" disabled>Select option</option><option value="comfortable">Comfortable</option><option value="needs_support">Needs event support</option><option value="prefer_not_to_say">Prefer not to say</option></select></label><label className="full-width">Optional note<textarea className="input textarea" name="note" rows={2} maxLength={1000} placeholder="Optional event-day context; do not include emergency or clinical information." /></label></>;
  if (entryType === "education") return <><label>Learning goal<input className="input" name="learningGoal" required minLength={2} maxLength={600} /></label><label className="full-width">Key takeaway<textarea className="input textarea" name="keyTakeaway" required rows={2} minLength={2} maxLength={1000} /></label><label className="full-width">Optional support topic<input className="input" name="supportTopic" maxLength={600} /></label></>;
  if (entryType === "community") return <><label>Participation intent<input className="input" name="participationIntent" required minLength={2} maxLength={600} /></label><label>Connection goal<input className="input" name="connectionGoal" required minLength={2} maxLength={600} /></label><label className="full-width">Optional feedback<textarea className="input textarea" name="feedback" rows={2} maxLength={1000} /></label></>;
  return <><label>Experience rating<select className="input" name="experienceRating" required defaultValue=""><option value="" disabled>Select 1–5</option>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>Highlight<input className="input" name="highlight" required minLength={2} maxLength={1000} /></label><label className="full-width">Optional feedback<textarea className="input textarea" name="feedback" rows={2} maxLength={1000} /></label></>;
}
const iconFor = (type: string) => type === "health" ? Activity : type === "education" ? BookOpen : type === "community" ? HeartHandshake : Sparkles;

export default function ParticipantHistoryWorkspace({ data }: { data: WorkspaceData }) {
  return <>
    <section className="panel"><span className="eyebrow"><ShieldCheck size={13} /> Your consent and history</span><h2>Event-day check-ins</h2><p>Entries are manual, dated, and append-only. They are not clinical records or medical advice. You can withdraw health-check-in consent at any time; withdrawal stops new health entries and does not change your prior records.</p><div className="split-actions"><div><b>Health check-in consent</b><p>{data.consent?.healthConsentGranted ? "Active. You may add health check-ins for eligible wellness and running events." : "Not active. Health check-ins remain unavailable until you explicitly agree."}</p></div><form action={setParticipantHealthConsentAction}><input type="hidden" name="healthConsentGranted" value={data.consent?.healthConsentGranted ? "false" : "true"} /><button className={data.consent?.healthConsentGranted ? "btn btn-outline" : "btn btn-coral"} type="submit">{data.consent?.healthConsentGranted ? "Withdraw consent" : "Give health consent"}</button></form></div></section>
    <section className="panel"><div className="section-head"><div><span className="eyebrow">Manual event entries</span><h2>Choose a registered event</h2><p>Single-day events accept one dated entry. Multi-day events show an **Add daily update** choice for each event date.</p></div></div>{data.registrations.length ? <div className="capability-card-grid">{data.registrations.map(({ registration, event, category, entryType, form, startDate, endDate }) => { const dates = datesBetween(startDate, endDate); const longEvent = dates.length > 1; const isHealth = entryType === "health"; const blocked = isHealth && !data.consent?.healthConsentGranted; return <article className="capability-card" key={registration.id}><span className="status-pill submitted">{category?.name || "Event"}</span><h3>{event.displayName}</h3><p>{form.description}</p><p><small>{longEvent ? "Multi-day event — add one daily update for each date." : "Single-day event — one dated entry."}</small></p>{blocked ? <div className="notice">Give explicit health consent above to unlock this voluntary health check-in.</div> : <form action={createParticipantHistoryEntryAction} className="capability-form"><input type="hidden" name="registrationId" value={registration.id} /><label>{longEvent ? "Add daily update for" : "Event date"}<select className="input" name="entryDate" defaultValue={dates[0] || ""} required>{dates.map(date => <option key={date} value={date}>{date}</option>)}</select></label><div className="scope-grid"><EntryFields entryType={entryType} /></div><button className="btn btn-coral" type="submit">{longEvent ? "Add daily update" : `Save ${form.title}`}</button></form>}</article>; })}</div> : <div className="empty-card"><h3>No confirmed event registrations yet</h3><p>After you register for an event, its category-aware check-in form appears here.</p></div>}</section>
    <section className="panel"><div className="section-head"><div><span className="eyebrow">Append-only history</span><h2>Your dated entries</h2><p>Corrections create a separate record and never overwrite the original entry.</p></div></div>{data.entries.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Entry</th><th>Date and category</th><th>Original record</th><th>Separate correction</th></tr></thead><tbody>{data.entries.map(entry => { const Icon = iconFor(entry.entryType); const corrections = data.corrections.filter(item => item.originalEntryId === entry.id); return <tr key={entry.id}><td><Icon size={16} /> <b>{entry.publicId}</b><br /><small>{entry.entryType} entry</small></td><td>{entry.entryDate}<br /><small>{entry.categorySlug}</small></td><td><small>Created {new Date(entry.createdAt).toLocaleString("en-IN")}</small><br /><small>Original remains immutable{corrections.length ? ` · ${corrections.length} correction${corrections.length === 1 ? "" : "s"}` : ""}</small></td><td><details><summary className="text-button"><PencilLine size={14} /> Add correction</summary><form action={createParticipantHistoryCorrectionAction} className="admin-control-stack"><input type="hidden" name="entryId" value={entry.id} /><textarea className="input textarea" name="reason" rows={2} minLength={8} required placeholder="Why a separate correction is needed" /><EntryFields entryType={entry.entryType} /><button className="btn btn-outline" type="submit">Record separate correction</button></form></details></td></tr>; })}</tbody></table></div> : <div className="empty-card"><h3>Your append-only history is empty</h3><p>Your first dated event entry will appear here with its immutable record ID.</p></div>}</section>
  </>;
}
