"use client";

import { Landmark, Smartphone, Ticket } from "lucide-react";
import { useState } from "react";
import { registerAction, submitPaymentProofAction } from "../actions";
import PaymentProofUpload from "./PaymentProofUpload";

type TicketOption = { id: number; name: string; pricePaise: number; ticketCategory: "paid" | "free" | "donation"; gstApplicable: boolean; gstRatePercent: number; platformFeePayer: "organizer" | "buyer"; fitizenFeePayer: "organizer" | "buyer"; gatewayFeePayer: "organizer" | "buyer" };
type ManualPayment = { enabled: boolean; method: "upi" | "bank" | "both" | null; upiId?: string | null; bankAccountName?: string | null; bankAccountNumber?: string | null; bankIfsc?: string | null; bankName?: string | null; note?: string | null };
type Booking = { orderNumber: string; paymentStatus: "not_required" | "pending" | "paid" | "failed" | "refunded"; paidAmountPaise: number; manualPaymentReference?: string | null; paymentProofUrl?: string | null; paymentRejectionNote?: string | null };
type ExistingRegistration = { orderNumber: string; paymentStatus: Booking["paymentStatus"] };

export default function RegistrationPanel({ eventId, eventPublicId, userPublicId, slug, tickets, platformFeePercent, gatewayFeePercent = 0, manualPayment, booking, existingRegistration, paymentNotice }: { eventId: number; eventPublicId: string; userPublicId?: string; slug: string; tickets: TicketOption[]; platformFeePercent: number; gatewayFeePercent?: number; manualPayment: ManualPayment; booking?: Booking; existingRegistration?: ExistingRegistration; paymentNotice?: string }) {
  const [ticketId, setTicketId] = useState(String(tickets[0]?.id || ""));
  const selected = tickets.find(ticket => String(ticket.id) === ticketId);
  const isPaid = Boolean(selected && selected.ticketCategory !== "free" && selected.pricePaise > 0);
  const gstPaise = selected?.gstApplicable ? Math.round(selected.pricePaise * selected.gstRatePercent / 100) : 0;
  const platformFeePaise = selected?.platformFeePayer === "buyer" ? Math.round(selected.pricePaise * platformFeePercent / 100) : 0;
  const gatewayFeePaise = selected?.gatewayFeePayer === "buyer" ? Math.round(selected.pricePaise * gatewayFeePercent / 100) : 0;
  const totalPaise = selected ? selected.pricePaise + gstPaise + platformFeePaise + gatewayFeePaise : 0;
  const money = (paise: number) => `₹${(paise / 100).toLocaleString("en-IN")}`;
  const upiVisible = manualPayment.enabled && (manualPayment.method === "upi" || manualPayment.method === "both") && manualPayment.upiId;
  const bankVisible = manualPayment.enabled && (manualPayment.method === "bank" || manualPayment.method === "both") && manualPayment.bankAccountName && manualPayment.bankAccountNumber && manualPayment.bankIfsc;
  const paymentAvailable = Boolean(upiVisible || bankVisible);
  const identity = <p className="identifier-note"><b>Event ID:</b> {eventPublicId}{userPublicId ? <><br /><b>Your user ID:</b> {userPublicId}</> : null}</p>;

  if (!tickets.length) return <p role="status">Registration is coming soon for this event.</p>;
  if (existingRegistration && (!booking || booking.orderNumber !== existingRegistration.orderNumber || (booking.paymentStatus !== "pending" && booking.paymentStatus !== "failed"))) return <section className="ticket-box existing-registration" aria-label="Existing event registration"><span className="eyebrow">Already registered</span><h3>Your place is already reserved</h3><p>You are verified for this event by your permanent user ID and this event ID.</p>{identity}<p><b>Booking reference:</b> {existingRegistration.orderNumber}</p><a className="btn btn-outline" href="/dashboard/my-bookings">View My Registrations</a></section>;
  if (booking && booking.paymentStatus !== "paid" && booking.paymentStatus !== "not_required") return <section className="ticket-box payment-booking-flow" aria-label="Complete manual payment"><span className="eyebrow">Booking created</span><h3>Booking #{booking.orderNumber}</h3>{identity}{paymentNotice === "submitted" ? <p className="success-note">Payment proof submitted. The organizer will review it shortly.</p> : null}{paymentNotice === "error" ? <p className="error-note">We could not submit that proof. Please upload it again.</p> : null}{booking.paymentStatus === "failed" ? <div className="error-note"><b>Payment proof needs an update.</b><br />{booking.paymentRejectionNote || "The organizer asked you to resubmit your payment proof."}</div> : null}{booking.paymentProofUrl && booking.paymentStatus === "pending" ? <div className="payment-review-state"><b>Proof submitted for review</b><span>Reference: {booking.manualPaymentReference || "Not provided"}</span><a href={booking.paymentProofUrl} target="_blank" rel="noreferrer">View uploaded proof</a></div> : <><p>Transfer <b>₹{(booking.paidAmountPaise / 100).toLocaleString("en-IN")}</b> using the organizer details below. Your booking reference is available for the transfer note if your payment app supports it.</p>{upiVisible ? <div className="attendee-payment-detail"><Smartphone size={17} /><div><span>UPI ID</span><b>{manualPayment.upiId}</b></div></div> : null}{bankVisible ? <div className="attendee-payment-detail"><Landmark size={17} /><div><span>Bank transfer</span><b>{manualPayment.bankAccountName}</b><small>{manualPayment.bankName ? `${manualPayment.bankName} · ` : ""}A/C {manualPayment.bankAccountNumber} · IFSC {manualPayment.bankIfsc}</small></div></div> : null}{manualPayment.note ? <p className="manual-payment-note">{manualPayment.note}</p> : null}<form action={submitPaymentProofAction} className="proof-submit-form"><input type="hidden" name="orderNumber" value={booking.orderNumber} /><input type="hidden" name="slug" value={slug} /><label className="form-label">Transaction reference <span className="optional">Optional</span><input className="input" name="manualPaymentReference" maxLength={128} placeholder="UTR, UPI reference, or transaction ID" /></label><PaymentProofUpload orderNumber={booking.orderNumber} /><button className="btn btn-coral" type="submit">Submit proof for review</button></form></>}</section>;
  return <form action={registerAction} className="ticket-box" aria-label="Event registration"><input type="hidden" name="eventId" value={eventId} /><h3><Ticket size={18} aria-hidden="true" /> Choose your ticket</h3>{userPublicId ? <p className="identifier-note">Your registration is verified using <b>{userPublicId}</b> for event <b>{eventPublicId}</b>.</p> : null}<select className="select" name="ticketId" aria-label="Choose a ticket" value={ticketId} onChange={event => setTicketId(event.target.value)}>{tickets.map(ticket => { const gst = ticket.gstApplicable ? Math.round(ticket.pricePaise * ticket.gstRatePercent / 100) : 0; const platformFee = ticket.platformFeePayer === "buyer" ? Math.round(ticket.pricePaise * platformFeePercent / 100) : 0; const gatewayFee = ticket.gatewayFeePayer === "buyer" ? Math.round(ticket.pricePaise * gatewayFeePercent / 100) : 0; return <option key={ticket.id} value={ticket.id}>{ticket.name} — {ticket.pricePaise ? money(ticket.pricePaise + gst + platformFee + gatewayFee) : "Free"}</option>; })}</select>{isPaid && selected ? <div className="checkout-notice checkout-breakdown" aria-live="polite"><b>Buyer price breakdown</b><div><span>Ticket price</span><strong>{money(selected.pricePaise)}</strong></div><div><span>GST {selected.gstApplicable ? `(${selected.gstRatePercent}%)` : "(not applicable)"}</span><strong>{money(gstPaise)}</strong></div><div><span>Platform fee {selected.platformFeePayer === "buyer" ? `(${platformFeePercent}%)` : "(covered by organizer)"}</span><strong>{selected.platformFeePayer === "buyer" ? money(platformFeePaise) : "₹0"}</strong></div><div><span>Nexriva service allocation</span><strong>{selected.fitizenFeePayer === "buyer" ? "No separate amount configured" : "Covered by organizer"}</strong></div><div><span>Gateway fee {selected.gatewayFeePayer === "buyer" ? `(${gatewayFeePercent}%)` : "(covered by organizer)"}</span><strong>{selected.gatewayFeePayer === "buyer" ? money(gatewayFeePaise) : "₹0"}</strong></div><div className="checkout-breakdown-total"><span>Total payable</span><strong>{money(totalPaise)}</strong></div><p>Reserve your ticket to create the booking reference, then use the organizer&apos;s payment instructions and upload proof.</p></div> : null}<button className="btn btn-coral" disabled={isPaid && !paymentAvailable} type="submit">{isPaid ? "Reserve ticket & get booking reference" : "Register now"}</button>{isPaid && !paymentAvailable ? <p className="error-note">The organizer has not completed payment instructions for this ticket yet.</p> : null}</form>;
}
