import Link from "next/link";
import { headers } from "next/headers";
import { CalendarPlus } from "lucide-react";
import DashboardShell from "../../../components/DashboardShell";
import EventCard from "../../../components/EventCard";
import VenueAvailabilityInbox from "../../../components/VenueAvailabilityInbox";
import { currentUser } from "../../../lib/auth";
import { getOrganizerEvents, getOrganizerVenueAvailabilityNotifications } from "../../../lib/db";
import { completeOrganizerEventAction } from "../../../actions";

export default async function ManageEvents({ searchParams }: { searchParams: Promise<{ status?: "live" | "completed" | "draft" | "submitted" | "changes" | "frozen" | "suspended" | "deleted"; submitted?: string; completed?: string; error?: string }> }) {
  const user = await currentUser(); if (!user) return null;
  const requestHeaders = await headers(); const host = (requestHeaders.get("x-forwarded-host") || requestHeaders.get("host") || "").split(",")[0].trim(); const protocol = (requestHeaders.get("x-forwarded-proto") || (host.includes("localhost") ? "http" : "https")).split(",")[0].trim(); const origin = host ? `${protocol}://${host}` : "";
  const { status = "live", submitted, completed, error } = await searchParams; const [events, venueNotifications] = await Promise.all([getOrganizerEvents(user.id, status), getOrganizerVenueAvailabilityNotifications(user.id)]); const labels = { live: "Live Events", completed: "Completed Events", draft: "Drafts", submitted: "Awaiting Approval", changes: "Changes Requested", frozen: "Frozen", suspended: "Suspended", deleted: "Removed" };
  return <DashboardShell active="My Events"><div className="dash-page-head"><div><h1 className="page-title">Your Events</h1><p>Track drafts, approval submissions, administrator feedback, and live events in one place.</p></div><Link className="btn btn-coral" href="/dashboard/manage-events/create-event/new"><CalendarPlus size={16} /> Create New Event</Link></div><VenueAvailabilityInbox notifications={venueNotifications} />{submitted ? <div className="success-note">Your event has been submitted to the administrator for approval.</div> : null}{completed ? <div className="success-note">Event completed. Its approved venue is now available for another event.</div> : null}{error ? <div className="error-note">{error}</div> : null}<div className="tabs"><Link className={status === "live" ? "active" : ""} href="/dashboard/manage-events/events?status=live">Live Events</Link><Link className={status === "submitted" ? "active" : ""} href="/dashboard/manage-events/events?status=submitted">Awaiting Approval</Link><Link className={status === "changes" ? "active" : ""} href="/dashboard/manage-events/events?status=changes">Changes Requested</Link><Link className={status === "draft" ? "active" : ""} href="/dashboard/manage-events/events?status=draft">Drafts</Link><Link className={status === "completed" ? "active" : ""} href="/dashboard/manage-events/events?status=completed">Completed</Link></div>{events.length ? <div className="event-grid organizer-grid">{events.map(({ event, category, registration }) => <div className="organizer-event-card" key={event.id}><EventCard event={event} category={category} registration={registration} adminHref={`/dashboard/manage-events/create-event/${event.id}`} origin={origin} />{status === "live" ? <form action={completeOrganizerEventAction} className="complete-event-action"><input type="hidden" name="eventId" value={event.id} /><button className="text-button" type="submit">Mark completed &amp; release venue</button></form> : null}</div>)}</div> : <div className="empty-card"><h3>No {labels[status]} yet.</h3><p>{status === "draft" ? "Start a new event and your draft will be auto-saved as you work." : status === "submitted" ? "Submitted events appear here while the administrator reviews their content, pricing, and platform fee." : "Create an event, complete all six steps, and submit it for administrator approval."}</p><Link className="btn btn-coral" href="/dashboard/manage-events/create-event/new">Create New Event</Link></div>}</DashboardShell>;
}
