import { Check, Compass, HeartHandshake, MapPinned, Medal, MonitorCog, UsersRound } from "lucide-react";
import SiteFooter from "../components/SiteFooter";
import SiteNav from "../components/SiteNav";

const services = [["Community Event Tools", "Plan registrations, participant communications, venue details and live event information from one workspace."], ["Wellness and Learning Experiences", "Support runs, workshops, meetups, education sessions and local community activity with flexible event setup."], ["Organizer Operations", "Give organizers practical tools for ticketing, approvals, payment review, exports and attendee communication."]];
const strengths = [[HeartHandshake, "Participant-First", "Clear joining instructions and accessible registration paths."], [Compass, "Practical Discovery", "Find events by interest, place, accessibility and date."], [MonitorCog, "Workflow-Aware", "Built around organizer, participant, sponsor and authority workspaces."], [MapPinned, "Local Context", "Venue details support city, area, access and scheduling needs."], [UsersRound, "Shared Operations", "Useful coordination between organizers and approved collaborators."], [Medal, "Community Focus", "Designed for experiences that keep people participating."]] as const;
const values = [["Clarity", "Straightforward information, pricing and approval state."], ["Respect", "Role-specific access that protects participant and organizer data."], ["Inclusion", "Venue and discovery information that supports accessible choices."], ["Accountability", "Audited administrative actions and transparent workflow state."], ["Steady Improvement", "A platform that learns from real event operations."]];

export default function About() { return <><SiteNav /><main id="main-content"><section className="about-hero"><div className="shell about-hero-grid"><div><span className="eyebrow">About Nexriva</span><h1>Make room for <em>shared experiences.</em></h1><p>Nexriva is a neutral event-management workspace for discovering, organizing and supporting community experiences across India.</p></div><div className="about-mark"><span>NEXRIVA EVENTS</span><b>Built around every participant.</b><small>Community-led · India-wide · Event-ready</small></div></div></section><section className="shell impact-grid"><div><b>One</b><span>Connected event workspace</span></div><div><b>Many</b><span>Ways to participate</span></div><div><b>Clear</b><span>Roles and workflows</span></div></section><section className="section shell editorial-grid"><div className="section-kicker">Our Approach</div><div><h2>Start with the people attending.</h2><p>Nexriva brings together public discovery, event setup, registrations, venues and participation workflows in one adaptable product.</p><p>It supports organizer-led events while keeping sponsorship and authority access separate through reviewed, role-specific workspaces.</p></div></section><section className="about-surface"><div className="shell section"><div className="section-head"><div><span className="eyebrow">What We Do</span><h2>Useful event operations in one place.</h2></div><p>From small community sessions to city-scale activity, the workspace is designed to keep plans understandable and action-oriented.</p></div><div className="service-grid">{services.map(([title, copy], index) => <article className="service-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="section shell"><div className="section-head"><div><span className="eyebrow">Why Nexriva</span><h2>Tools shaped around real event work.</h2></div></div><div className="strength-grid">{strengths.map(([Icon, title, copy]) => <article key={title}><Icon size={20} /><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="mission-band"><div className="shell"><span>Our Mission</span><blockquote>To make community events easier to discover, organize and support with clear information and accountable workflows.</blockquote><p>Every workspace is designed to contribute to a smoother participant experience.</p><b>Built for organizers. Useful for participants. Ready for communities.</b></div></section><section className="section shell"><div className="section-head"><div><span className="eyebrow">Our Values</span><h2>What we stand for</h2></div></div><div className="values-list">{values.map(([title, copy]) => <article key={title}><Check size={18} /><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section></main><SiteFooter /></>; }
