import Link from "next/link";
import { CalendarDays, Grid2X2, List, Search } from "lucide-react";
import DashboardShell from "../../components/DashboardShell";
import { currentUser } from "../../lib/auth";
import { getFollowCount, getRegistrations } from "../../lib/db";

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

export default async function MyBookings({ searchParams }: { searchParams: Promise<{ layout?: "list" | "grid"; success?: string; pending?: string; submitted?: string; rejected?: string }> }) {
  const user = await currentUser(); if (!user) return null;
  const { layout = "list", success, pending, submitted, rejected } = await searchParams;
  const [records, follows] = await Promise.all([getRegistrations(user.id), getFollowCount(user.id)]); const now = Date.now(); const attended = records.filter(row => row.event.endsAt && new Date(row.event.endsAt).getTime() < now).length; const upcoming = records.filter(row => row.event.startsAt && new Date(row.event.startsAt).getTime() >= now).length; const activeMonths = new Set(records.map(row => row.event.startsAt ? new Date(row.event.startsAt).getUTCMonth() : -1)); const currentYear = new Date().getUTCFullYear();
  return <DashboardShell active="" mode="participant"><div className="dash-page-head"><div><span className="eyebrow">Attending</span><h1 className="page-title" style={{ marginTop: 11 }}>My Registrations</h1><p>Your event registrations and tickets.</p></div><div className="layout-toggle"><Link href="/dashboard/my-bookings?layout=list" className={`toggle ${layout === "list" ? "active" : ""}`}><List size={15} /> List</Link><Link href="/dashboard/my-bookings?layout=grid" className={`toggle ${layout === "grid" ? "active" : ""}`}><Grid2X2 size={15} /> Grid</Link></div></div>{success ? <div className="notice">Your registration is confirmed. Registration ID: {success}</div> : null}{pending ? <div className="notice">Your booking is ready. Use its booking ID when available in your payment app, then upload payment proof from the event page.</div> : null}{submitted ? <div className="notice">Payment proof submitted. The organizer will review booking {submitted}.</div> : null}{rejected ? <div className="error-note">Your payment proof needs an update. Open the event page from your ticket below to review the note and upload a new proof.</div> : null}<section className="panel"><span className="eyebrow">Attending</span><h3>Good morning!</h3><p>Welcome, {user.name || "event lover"}! Let&apos;s find your first race. <Link href="/events" className="link-arrow">Find Your First Race →</Link></p></section><section className="stats-grid"><div className="stat-card"><b>{attended}</b><span>Events attended</span></div><div className="stat-card"><b>{upcoming}</b><span>Upcoming</span></div><div className="stat-card"><b>{follows}</b><span>Events followed</span></div></section><section className="panel"><h3>Your race year</h3><p>Each dot is a month in {currentYear}.</p><div className="timeline">{Array.from({ length: 12 }, (_, index) => <i className={activeMonths.has(index) ? "active" : ""} key={index} />)}</div><p>{records.length} events in 1 years</p></section><section className="panel"><div className="section-head"><div><h2 style={{ fontSize: 24 }}>My ticket wallet</h2><p>Your tickets and payment details are ready here.</p></div><Link href="/events" className="btn btn-outline btn-small"><Search size={15} /> Discover Events</Link></div>{records.length ? <div className={layout === "grid" ? "event-grid" : "registration-list"}>{records.map(({ registration, event, ticket }) => {
    const payment = registration.paymentStatus === "paid" ? `Payment confirmed · ₹${(registration.paidAmountPaise / 100).toLocaleString("en-IN")}` : registration.paymentStatus === "pending" ? registration.paymentProofUrl ? `Proof submitted · awaiting organizer review${registration.manualPaymentReference ? ` · Ref ${registration.manualPaymentReference}` : ""}` : "Booking created · upload payment proof" : registration.paymentStatus === "failed" ? `Payment proof rejected${registration.paymentRejectionNote ? ` · ${registration.paymentRejectionNote}` : ""}` : registration.paidAmountPaise ? `₹${(registration.paidAmountPaise / 100).toLocaleString("en-IN")}` : "Free registration";
    const proofHref = registration.paymentStatus === "pending" || registration.paymentStatus === "failed" ? `/events/${event.slug}?booking=${registration.orderNumber}` : undefined;
    const invoiceHref = registration.paymentStatus === "paid" ? `/api/invoices/${encodeURIComponent(registration.orderNumber)}` : undefined;
    const eventDate = event.startsAt ? (() => { const d = new Date(event.startsAt); return `${String(d.getUTCDate()).padStart(2, "0")} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`; })() : "Date to be confirmed";
    return layout === "grid" ? <div className="event-card" key={registration.id}><div className="event-card-copy"><div className="event-meta"><span>{registration.status.replace("_", " ")}</span><span>#{registration.orderNumber}</span></div><h3>{event.displayName}</h3><p><CalendarDays size={13} /> {eventDate}</p><p>{ticket?.name || "Registration"} · {payment}</p><p className="identifier-note">Registration ID: {registration.registrationNumber}</p>{proofHref ? <Link href={proofHref} className="text-button">{registration.paymentStatus === "failed" ? "Update payment proof" : "Complete payment proof"}</Link> : null}{invoiceHref ? <a href={invoiceHref} className="text-button">Download PDF tax invoice</a> : null}</div></div> : <div className="registration-row" key={registration.id}><div><b>{event.displayName}</b><p>{ticket?.name || "Registration"} · {payment} · Booking #{registration.orderNumber} · Registration ID {registration.registrationNumber}</p>{proofHref ? <Link href={proofHref} className="text-button">{registration.paymentStatus === "failed" ? "Update payment proof" : "Complete payment proof"}</Link> : null}{invoiceHref ? <a href={invoiceHref} className="text-button">Download PDF tax invoice</a> : null}</div><span className={`status ${registration.status === "checked_in" ? "" : registration.status === "cancelled" ? "completed" : "draft"}`}>{registration.status.replace("_", " ")}</span></div>;
  })}</div> : <div className="empty-card"><h3>No registrations yet</h3><p>When you register for an event, it will show up here with ticket and payment details.</p><Link className="btn btn-coral" href="/events">Find Your First Race →</Link></div>}</section></DashboardShell>;
}
