import { ArrowLeft, LogIn, Settings2 } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { saveWorkspaceLandingPreferenceAction } from "../../../actions";
import DashboardShell from "../../../components/DashboardShell";
import { currentUser } from "../../../lib/auth";
import { isWorkspaceLandingPreferencesEnabled } from "../../../lib/capability-feature";
import { getActiveCapabilityWorkspaces, getWorkspaceLandingPreference } from "../../../lib/db";

export default async function WorkspaceLandingPreferencesPage({ searchParams }: { searchParams: Promise<{ updated?: string; error?: string }> }) {
  const user = await currentUser(); if (!user) return null;
  if (!isWorkspaceLandingPreferencesEnabled()) redirect("/dashboard/my-bookings");
  const query = await searchParams; const [preference, workspaces] = await Promise.all([getWorkspaceLandingPreference(user.id), getActiveCapabilityWorkspaces(user.id)]);
  const selectedView = preference?.defaultView || "participant"; const selectedGrantId = preference?.defaultCapabilityGrantId || "";
  return <DashboardShell active="Workspaces" mode="participant"><div className="dash-page-head"><div><span className="eyebrow"><Settings2 size={13} /> Personal workspace setting</span><h1 className="page-title">Default view on login</h1><p>Choose a standard view or one currently approved capability workspace. A saved capability choice is revalidated every sign-in and falls back safely if it later expires or is suspended.</p></div><Link className="btn btn-outline" href="/dashboard/workspaces"><ArrowLeft size={15} /> All workspaces</Link></div>{query.error ? <div className="error-note" role="alert">{query.error}</div> : null}{query.updated ? <div className="notice" role="status">{query.updated}</div> : null}<section className="panel"><form action={saveWorkspaceLandingPreferenceAction} className="venue-editor"><fieldset><legend>Open this view after a normal login</legend><label className="capability-inline-check"><input type="radio" name="defaultView" value="participant" defaultChecked={selectedView === "participant"} /><span><b>Participant home</b><small>Open My Bookings and the standard participant workspace.</small></span></label><label className="capability-inline-check"><input type="radio" name="defaultView" value="organizer" defaultChecked={selectedView === "organizer"} /><span><b>Organizer events</b><small>Open your event-management workspace.</small></span></label><label className="capability-inline-check"><input type="radio" name="defaultView" value="capability" defaultChecked={selectedView === "capability"} disabled={!workspaces.length} /><span><b>Approved capability workspace</b><small>{workspaces.length ? "Choose one current selected-function grant below." : "No active approved workspace is available to save."}</small></span></label></fieldset>{workspaces.length ? <label className="form-label">Approved workspace<select className="input" name="defaultCapabilityGrantId" defaultValue={selectedGrantId}><option value="">Choose an active workspace</option>{workspaces.map(workspace => <option key={workspace.grant.id} value={workspace.grant.id}>{workspace.capability.displayName} · {workspace.functions.length} selected function{workspace.functions.length === 1 ? "" : "s"}</option>)}</select></label> : null}<p className="field-note">This preference does not grant access. A link is used only if its grant, selected functions, capability, and dates are still valid on the server.</p><button className="btn btn-coral" type="submit"><LogIn size={15} /> Save default view</button></form></section></DashboardShell>;
}
