import DashboardShell from "../../components/DashboardShell";
import { createPromotionAction } from "../../actions";
import { currentUser } from "../../lib/auth";
import { getOrganizerEvents, getPromotions } from "../../lib/db";

export default async function Promotions() {
  const user = await currentUser(); if (!user) return null; const [events, promotions] = await Promise.all([getOrganizerEvents(user.id, "live"), getPromotions(user.id)]);
  return <DashboardShell active="Promotions"><div className="dash-page-head"><div><h1 className="page-title">Promotions</h1><p>Plan and track promotional activities for your events.</p></div></div><section className="panel"><h3>Create promotion</h3><p>Build a simple promotional activity linked to one of your Live Events.</p>{events.length ? <form action={createPromotionAction} className="promo-form"><label className="form-label compact">Promotion title<input className="input" name="title" placeholder="Early-bird Instagram launch" required /></label><label className="form-label compact">Event<select className="select" name="eventId">{events.map(({ event }) => <option key={event.id} value={event.id}>{event.displayName}</option>)}</select></label><label className="form-label compact">Channel<select className="select" name="channel"><option value="social">Social</option><option value="email">Email</option><option value="partner">Partner</option><option value="featured">Featured</option></select></label><label className="form-label compact">Budget (₹)<input className="input" type="number" min="0" name="budget" defaultValue="0" /></label><button className="btn btn-coral" type="submit">Save promotion</button></form> : <div className="empty-card"><h3>Promotions need a Live Event.</h3><p>Publish an event first, then create promotional activities here.</p></div>}</section><section className="panel"><h3>Promotion activity</h3>{promotions.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Promotion</th><th>Event</th><th>Channel</th><th>Budget</th><th>Status</th></tr></thead><tbody>{promotions.map(({ promotion, event }) => <tr key={promotion.id}><td><b>{promotion.title}</b></td><td>{event.displayName}</td><td>{promotion.channel}</td><td>₹{(promotion.budgetPaise / 100).toLocaleString("en-IN")}</td><td><span className="status draft">{promotion.status}</span></td></tr>)}</tbody></table></div> : <div className="empty-card"><h3>No promotions created.</h3><p>Campaign drafts, scheduled activities, and status tracking will appear in this list.</p></div>}</section></DashboardShell>;
}
